package com.example.lifeos.core.strings

import androidx.compose.runtime.compositionLocalOf

enum class AppLanguage { INDONESIAN, ENGLISH }

// Grouped into nested data classes (instead of one flat ~260-field constructor) because a
// single constructor with that many parameters can fail ART's bytecode verifier during
// Android Studio's incremental "Apply Changes" deploy (VerifyError: too many argument
// registers). Each group below stays well under that limit.

data class NavStrings(
    val navBeranda: String,
    val navNotes: String,
    val navHabit: String,
    val navPomodoro: String,
    val navLainnya: String,
)

data class LainnyaStrings(
    val lainnyaTitle: String,
    val comingSoon: String,
    val moduleMoneyManager: String,
    val moduleBelajar: String,
    val moduleJadwal: String,
    val moduleTargetHidup: String,
    val moduleAiAssistant: String,
    val moduleMoodTracker: String,
    val moduleCloudSync: String,
    val moduleDashboardStatistik: String,
    val moduleSettings: String,
)

data class SettingsStrings(
    val settingsTitle: String,
    val settingsThemeSection: String,
    val settingsThemeLight: String,
    val settingsThemeDark: String,
    val settingsThemeSystem: String,
    val settingsLanguageSection: String,
    val settingsLanguageIndonesian: String,
    val settingsLanguageEnglish: String,
    val settingsAboutSection: String,
    val settingsAboutDescription: String,
    val settingsAboutVersion: String,
    val settingsAboutTagline: String,
    val settingsAboutCreatorLabel: String,
    val settingsAboutCreatorName: String,
    val settingsDataSection: String,
    val settingsClearDataButton: String,
    val settingsClearDataConfirmTitle: String,
    val settingsClearDataConfirmText: String,
    val settingsClearDataConfirm: String,
    val settingsClearDataCancel: String,
    val settingsClearDataDone: String,
    val settingsPomodoroSection: String,
    val settingsPomodoroFocusLabel: String,
    val settingsPomodoroShortBreakLabel: String,
    val settingsPomodoroLongBreakLabel: String,
    val settingsMinutesTemplate: String,
    val settingsDecreaseContentDesc: String,
    val settingsIncreaseContentDesc: String,
)

data class SharedStrings(
    val untitledNote: String,
    val back: String,
    val cancel: String,
    val delete: String,
    val save: String,
)

data class BerandaStrings(
    val berandaGreetingMorning: String,
    val berandaGreetingAfternoon: String,
    val berandaGreetingEvening: String,
    val berandaGreetingNight: String,
    val berandaSubtitle: String,
    val berandaHabitCardTitle: String,
    val berandaHabitProgressTemplate: String,
    val berandaStatNotesLabel: String,
    val berandaStatNotesValueTemplate: String,
    val berandaStatPomodoroLabel: String,
    val berandaStatPomodoroValueTemplate: String,
    val berandaActivitiesTitle: String,
    val berandaHabitActivityEmpty: String,
    val berandaHabitActivityTemplate: String,
    val berandaNotesActivityEmpty: String,
    val berandaNotesActivityTemplate: String,
    val berandaPomodoroActivityEmpty: String,
    val berandaPomodoroActivityTemplate: String,
    val berandaHabitMotivationText: String,
    val berandaPomodoroMotivationText: String,
)

data class NotesStrings(
    val notesEmptyTitle: String,
    val notesEmptySubtitle: String,
    val notesAddContentDesc: String,
    val notesDeleteContentDesc: String,
    val notesDeleteDialogTitle: String,
    val notesDeleteDialogText: String,
    val notesChecklistDoneTemplate: String,
    val notesSearchPlaceholder: String,
    val notesSearchClearContentDesc: String,
    val notesSearchEmptyTitle: String,
    val notesSearchEmptySubtitle: String,
    val notesPinnedSectionTitle: String,
    val notesOthersSectionTitle: String,
    val notesPinContentDesc: String,
    val notesUnpinContentDesc: String,
    val notesAddChooseTypeTitle: String,
    val notesAddTypeText: String,
    val notesAddTypeDrawing: String,
    val notesDrawingLabel: String,
)

data class NoteEditorStrings(
    val noteEditorTitleEditing: String,
    val noteEditorTitleNew: String,
    val noteEditorDeleteContentDesc: String,
    val noteEditorSaveContentDesc: String,
    val noteEditorTitleLabel: String,
    val noteEditorContentLabel: String,
    val noteEditorChecklistHeader: String,
    val noteEditorChecklistPlaceholder: String,
    val noteEditorChecklistRemoveContentDesc: String,
    val noteEditorAddChecklistItem: String,
    val noteEditorColorLabel: String,
    val noteEditorColorDefaultContentDesc: String,
    val noteEditorColorCustomContentDesc: String,
    val noteEditorCustomColorTitle: String,
    val noteEditorCustomColorConfirm: String,
    val noteEditorCustomColorRed: String,
    val noteEditorCustomColorGreen: String,
    val noteEditorCustomColorBlue: String,
)

data class HabitStrings(
    val habitTitle: String,
    val habitEmptySubtitle: String,
    val habitAddContentDesc: String,
    val habitSummaryContentDesc: String,
    val habitAddDialogTitle: String,
    val habitNameLabel: String,
    val habitAdd: String,
    val habitDeleteContentDesc: String,
    val habitDeleteDialogTitle: String,
    val habitDeleteDialogText: String,
    val habitStreakTemplate: String,
)

data class HabitReminderStrings(
    val habitReminderNoneLabel: String,
    val habitReminderSetContentDesc: String,
    val habitReminderDialogTitle: String,
    val habitReminderClear: String,
    val habitReminderNotificationTitle: String,
    val habitReminderNotificationTextTemplate: String,
    val habitReminderChannelName: String,
    val habitReminderChannelDescription: String,
)

data class HabitSummaryStrings(
    val habitSummaryTitle: String,
    val habitSummaryDateLabel: String,
    val habitSummaryEmptyTitle: String,
    val habitSummaryEmptySubtitle: String,
    val habitSummaryDoneTemplate: String,
    val habitSummaryPick: String,
)

data class PomodoroStrings(
    val pomodoroTitle: String,
    val pomodoroPhaseFocus: String,
    val pomodoroPhaseShortBreak: String,
    val pomodoroPhaseLongBreak: String,
    val pomodoroResetContentDesc: String,
    val pomodoroPauseContentDesc: String,
    val pomodoroStartContentDesc: String,
    val pomodoroSkipContentDesc: String,
    val pomodoroSessionsTodayTemplate: String,
    val pomodoroHelpContentDesc: String,
    val pomodoroHelpTitle: String,
    val pomodoroHelpText: String,
    val pomodoroHelpConfirm: String,
    val pomodoroHistoryContentDesc: String,
)

data class PomodoroSummaryStrings(
    val pomodoroSummaryTitle: String,
    val pomodoroSummaryDateLabel: String,
    val pomodoroSummaryEmptyTitle: String,
    val pomodoroSummaryEmptySubtitle: String,
    val pomodoroSummaryCountTemplate: String,
    val pomodoroSummarySessionTimeTemplate: String,
)

data class DrawingStrings(
    val drawingEditorTitleNew: String,
    val drawingEditorTitleEditing: String,
    val drawingUndoContentDesc: String,
    val drawingClearContentDesc: String,
    val drawingClearConfirmTitle: String,
    val drawingClearConfirmText: String,
    val drawingTitlePlaceholder: String,
)

data class MoneyStrings(
    val moneySummaryIncome: String,
    val moneySummaryExpense: String,
    val moneySummaryBalance: String,
    val moneyEmptyTitle: String,
    val moneyEmptySubtitle: String,
    val moneyAddContentDesc: String,
    val moneyDeleteDialogTitle: String,
    val moneyDeleteDialogText: String,
    val moneyAddTransactionTitle: String,
    val moneyAmountLabel: String,
    val moneyCategoryLabel: String,
    val moneyDateLabel: String,
    val moneyNoteLabel: String,
    val moneyNotePlaceholder: String,
    val moneyCategoryFood: String,
    val moneyCategoryTransport: String,
    val moneyCategoryHousing: String,
    val moneyCategoryEntertainment: String,
    val moneyCategoryShopping: String,
    val moneyCategoryHealth: String,
    val moneyCategoryOtherExpense: String,
    val moneyCategoryAllowance: String,
    val moneyCategorySalary: String,
    val moneyCategoryBonus: String,
    val moneyCategoryOtherIncome: String,
    val moneyTabTransactions: String,
    val moneyTabSavings: String,
    val moneyTabInsights: String,
    val moneyStreakTemplate: String,
    val moneyStreakEmpty: String,
    val moneyInsightTopCategoryTemplate: String,
    val moneyInsightNoDataYet: String,
    val moneyInsightVsLastMonthUpTemplate: String,
    val moneyInsightVsLastMonthDownTemplate: String,
    val moneyBreakdownTitle: String,
    val moneyBreakdownEmpty: String,
    val moneyBudgetSectionTitle: String,
    val moneyBudgetPercentTemplate: String,
    val moneyBudgetOverTemplate: String,
    val moneyAddBudgetLabel: String,
    val moneySetBudgetTitle: String,
    val moneyBudgetLimitLabel: String,
    val moneyDeleteBudgetContentDesc: String,
    val moneyNoBudgetsYet: String,
)

data class SavingsStrings(
    val savingsEmptyTitle: String,
    val savingsEmptySubtitle: String,
    val savingsAddContentDesc: String,
    val savingsAddGoalTitle: String,
    val savingsGoalNameLabel: String,
    val savingsTargetAmountLabel: String,
    val savingsMonthlyContributionLabel: String,
    val savingsAnnualReturnLabel: String,
    val savingsAnnualReturnHint: String,
    val savingsEstimateLabel: String,
    val savingsEstimateAchieved: String,
    val savingsEstimateMonthsTemplate: String,
    val savingsEstimateYearsMonthsTemplate: String,
    val savingsEstimateNeverTemplate: String,
    val savingsProgressTemplate: String,
    val savingsDeleteGoalContentDesc: String,
    val savingsDeleteGoalDialogTitle: String,
    val savingsDeleteGoalDialogText: String,
    val savingsAddDepositContentDesc: String,
    val savingsAddDepositTitle: String,
    val savingsDepositAmountLabel: String,
    val savingsDepositHistoryTitle: String,
    val savingsNoDepositsYet: String,
    val savingsDeleteDepositDialogTitle: String,
    val savingsDeleteDepositDialogText: String,
)

data class JadwalStrings(
    val jadwalTitle: String,
    val jadwalEmptySubtitle: String,
    val jadwalAddContentDesc: String,
    val jadwalAddDialogTitle: String,
    val jadwalTitleLabel: String,
    val jadwalDateLabel: String,
    val jadwalTimeLabel: String,
    val jadwalTimeNoneLabel: String,
    val jadwalTimeDialogTitle: String,
    val jadwalClearTime: String,
    val jadwalAdd: String,
    val jadwalDeleteContentDesc: String,
    val jadwalDeleteDialogTitle: String,
    val jadwalDeleteDialogText: String,
    val jadwalReminderChannelName: String,
    val jadwalReminderChannelDescription: String,
    val jadwalReminderNotificationTitle: String,
    val jadwalReminderNotificationTextTemplate: String,
)

data class TargetHidupStrings(
    val targetHidupTitle: String,
    val targetHidupEmptySubtitle: String,
    val targetHidupAddContentDesc: String,
    val targetHidupAddDialogTitle: String,
    val targetHidupTitleLabel: String,
    val targetHidupTargetDateLabel: String,
    val targetHidupTargetDateNoneLabel: String,
    val targetHidupProgressLabel: String,
    val targetHidupProgressTemplate: String,
    val targetHidupAdd: String,
    val targetHidupEditDialogTitle: String,
    val targetHidupDeleteContentDesc: String,
    val targetHidupDeleteDialogTitle: String,
    val targetHidupDeleteDialogText: String,
    val targetHidupCompletedLabel: String,
    val targetHidupDaysLeftTemplate: String,
    val targetHidupOverdueLabel: String,
)

data class StatistikStrings(
    val statistikTitle: String,
    val statistikTotalNotes: String,
    val statistikTotalPomodoro: String,
    val statistikActiveHabits: String,
    val statistikLongestStreak: String,
    val statistikStreakTemplate: String,
    val statistikGoalsAchieved: String,
    val statistikPomodoroChartTitle: String,
    val statistikHabitChartTitle: String,
    val statistikTodayLabel: String,
    val statistikDonutCompletedLabel: String,
    val statistikDonutRemainingLabel: String,
    val statistikDonutTodayTemplate: String,
    val statistikDonutAvgTemplate: String,
)

data class AiAssistantStrings(
    val aiAssistantTitle: String,
    val aiAssistantEmptySubtitle: String,
    val aiAssistantInputPlaceholder: String,
    val aiAssistantSendContentDesc: String,
    val aiAssistantClearContentDesc: String,
    val aiAssistantClearDialogTitle: String,
    val aiAssistantClearDialogText: String,
    val aiAssistantRateLimitMessage: String,
    val aiAssistantErrorPrefixTemplate: String,
    val aiAssistantThinkingLabel: String,
)

data class BelajarStrings(
    val belajarTitle: String,
    val belajarSubjectMatematika: String,
    val belajarSubjectBahasaInggris: String,
    val belajarSubjectFisika: String,
    val belajarSubjectKimia: String,
    val belajarSubjectMusik: String,
    val belajarSubjectSeni: String,
)

data class BahasaInggrisGameStrings(
    val bahasaInggrisGameKosakata: String,
    val bahasaInggrisGameTataBahasa: String,
    val bahasaInggrisGameSusunKalimat: String,
    val bahasaInggrisGameListening: String,
)

data class KosakataStrings(
    val kosakataDescription: String,
    val kosakataScoreTemplate: String,
    val kosakataQuestionTitleTemplate: String,
    val kosakataCorrectFeedback: String,
    val kosakataIncorrectFeedback: String,
    val kosakataNextQuestion: String,
    val kosakataBackToList: String,
    val kosakataAllDoneMessage: String,
)

data class TataBahasaStrings(
    val tataBahasaDescription: String,
    val tataBahasaScoreTemplate: String,
    val tataBahasaQuestionTitleTemplate: String,
    val tataBahasaCorrectFeedback: String,
    val tataBahasaIncorrectFeedback: String,
    val tataBahasaNextQuestion: String,
    val tataBahasaBackToList: String,
    val tataBahasaAllDoneMessage: String,
)

data class SusunKalimatStrings(
    val susunKalimatDescription: String,
    val susunKalimatScoreTemplate: String,
    val susunKalimatQuestionTitleTemplate: String,
    val susunKalimatCorrectFeedback: String,
    val susunKalimatIncorrectFeedback: String,
    val susunKalimatNextQuestion: String,
    val susunKalimatBackToList: String,
    val susunKalimatAllDoneMessage: String,
    val susunKalimatCheckButton: String,
    val susunKalimatResetButton: String,
    val susunKalimatHintLabel: String,
)

data class ListeningStrings(
    val listeningDescription: String,
    val listeningScoreTemplate: String,
    val listeningQuestionTitleTemplate: String,
    val listeningCorrectFeedback: String,
    val listeningIncorrectFeedback: String,
    val listeningNextQuestion: String,
    val listeningBackToList: String,
    val listeningAllDoneMessage: String,
    val listeningPlayButton: String,
    val listeningPrompt: String,
)

data class FisikaGameStrings(
    val fisikaGameBesaran: String,
    val fisikaGameGerak: String,
    val fisikaGameEnergi: String,
    val fisikaGameListrik: String,
)

data class FisikaBesaranStrings(
    val fisikaBesaranDescription: String,
    val fisikaBesaranScoreTemplate: String,
    val fisikaBesaranQuestionTitleTemplate: String,
    val fisikaBesaranCorrectFeedback: String,
    val fisikaBesaranIncorrectFeedback: String,
    val fisikaBesaranNextQuestion: String,
    val fisikaBesaranBackToList: String,
    val fisikaBesaranAllDoneMessage: String,
)

data class FisikaGerakStrings(
    val fisikaGerakDescription: String,
    val fisikaGerakScoreTemplate: String,
    val fisikaGerakQuestionTitleTemplate: String,
    val fisikaGerakCorrectFeedback: String,
    val fisikaGerakIncorrectFeedback: String,
    val fisikaGerakNextQuestion: String,
    val fisikaGerakBackToList: String,
    val fisikaGerakAllDoneMessage: String,
)

data class FisikaEnergiStrings(
    val fisikaEnergiDescription: String,
    val fisikaEnergiScoreTemplate: String,
    val fisikaEnergiQuestionTitleTemplate: String,
    val fisikaEnergiCorrectFeedback: String,
    val fisikaEnergiIncorrectFeedback: String,
    val fisikaEnergiNextQuestion: String,
    val fisikaEnergiBackToList: String,
    val fisikaEnergiAllDoneMessage: String,
)

data class FisikaListrikStrings(
    val fisikaListrikDescription: String,
    val fisikaListrikScoreTemplate: String,
    val fisikaListrikQuestionTitleTemplate: String,
    val fisikaListrikCorrectFeedback: String,
    val fisikaListrikIncorrectFeedback: String,
    val fisikaListrikNextQuestion: String,
    val fisikaListrikBackToList: String,
    val fisikaListrikAllDoneMessage: String,
)

data class KimiaGameStrings(
    val kimiaGameAtom: String,
    val kimiaGameIkatan: String,
    val kimiaGameAsamBasa: String,
    val kimiaGameWujud: String,
)

data class KimiaAtomStrings(
    val kimiaAtomDescription: String,
    val kimiaAtomScoreTemplate: String,
    val kimiaAtomQuestionTitleTemplate: String,
    val kimiaAtomCorrectFeedback: String,
    val kimiaAtomIncorrectFeedback: String,
    val kimiaAtomNextQuestion: String,
    val kimiaAtomBackToList: String,
    val kimiaAtomAllDoneMessage: String,
)

data class KimiaIkatanStrings(
    val kimiaIkatanDescription: String,
    val kimiaIkatanScoreTemplate: String,
    val kimiaIkatanQuestionTitleTemplate: String,
    val kimiaIkatanCorrectFeedback: String,
    val kimiaIkatanIncorrectFeedback: String,
    val kimiaIkatanNextQuestion: String,
    val kimiaIkatanBackToList: String,
    val kimiaIkatanAllDoneMessage: String,
)

data class KimiaAsamBasaStrings(
    val kimiaAsamBasaDescription: String,
    val kimiaAsamBasaScoreTemplate: String,
    val kimiaAsamBasaQuestionTitleTemplate: String,
    val kimiaAsamBasaCorrectFeedback: String,
    val kimiaAsamBasaIncorrectFeedback: String,
    val kimiaAsamBasaNextQuestion: String,
    val kimiaAsamBasaBackToList: String,
    val kimiaAsamBasaAllDoneMessage: String,
)

data class KimiaWujudStrings(
    val kimiaWujudDescription: String,
    val kimiaWujudScoreTemplate: String,
    val kimiaWujudQuestionTitleTemplate: String,
    val kimiaWujudCorrectFeedback: String,
    val kimiaWujudIncorrectFeedback: String,
    val kimiaWujudNextQuestion: String,
    val kimiaWujudBackToList: String,
    val kimiaWujudAllDoneMessage: String,
)

data class MusikGameStrings(
    val musikGameNotNada: String,
    val musikGameRitme: String,
    val musikGameAlat: String,
    val musikGameTeori: String,
)

data class MusikNotNadaStrings(
    val musikNotNadaDescription: String,
    val musikNotNadaScoreTemplate: String,
    val musikNotNadaQuestionTitleTemplate: String,
    val musikNotNadaCorrectFeedback: String,
    val musikNotNadaIncorrectFeedback: String,
    val musikNotNadaNextQuestion: String,
    val musikNotNadaBackToList: String,
    val musikNotNadaAllDoneMessage: String,
)

data class MusikRitmeStrings(
    val musikRitmeDescription: String,
    val musikRitmeScoreTemplate: String,
    val musikRitmeQuestionTitleTemplate: String,
    val musikRitmeCorrectFeedback: String,
    val musikRitmeIncorrectFeedback: String,
    val musikRitmeNextQuestion: String,
    val musikRitmeBackToList: String,
    val musikRitmeAllDoneMessage: String,
)

data class MusikAlatStrings(
    val musikAlatDescription: String,
    val musikAlatScoreTemplate: String,
    val musikAlatQuestionTitleTemplate: String,
    val musikAlatCorrectFeedback: String,
    val musikAlatIncorrectFeedback: String,
    val musikAlatNextQuestion: String,
    val musikAlatBackToList: String,
    val musikAlatAllDoneMessage: String,
)

data class MusikTeoriStrings(
    val musikTeoriDescription: String,
    val musikTeoriScoreTemplate: String,
    val musikTeoriQuestionTitleTemplate: String,
    val musikTeoriCorrectFeedback: String,
    val musikTeoriIncorrectFeedback: String,
    val musikTeoriNextQuestion: String,
    val musikTeoriBackToList: String,
    val musikTeoriAllDoneMessage: String,
)

data class SeniGameStrings(
    val seniGameWarna: String,
    val seniGameUnsur: String,
    val seniGameTeknik: String,
    val seniGameAliran: String,
)

data class SeniWarnaStrings(
    val seniWarnaDescription: String,
    val seniWarnaScoreTemplate: String,
    val seniWarnaQuestionTitleTemplate: String,
    val seniWarnaCorrectFeedback: String,
    val seniWarnaIncorrectFeedback: String,
    val seniWarnaNextQuestion: String,
    val seniWarnaBackToList: String,
    val seniWarnaAllDoneMessage: String,
)

data class SeniUnsurStrings(
    val seniUnsurDescription: String,
    val seniUnsurScoreTemplate: String,
    val seniUnsurQuestionTitleTemplate: String,
    val seniUnsurCorrectFeedback: String,
    val seniUnsurIncorrectFeedback: String,
    val seniUnsurNextQuestion: String,
    val seniUnsurBackToList: String,
    val seniUnsurAllDoneMessage: String,
)

data class SeniTeknikStrings(
    val seniTeknikDescription: String,
    val seniTeknikScoreTemplate: String,
    val seniTeknikQuestionTitleTemplate: String,
    val seniTeknikCorrectFeedback: String,
    val seniTeknikIncorrectFeedback: String,
    val seniTeknikNextQuestion: String,
    val seniTeknikBackToList: String,
    val seniTeknikAllDoneMessage: String,
)

data class SeniAliranStrings(
    val seniAliranDescription: String,
    val seniAliranScoreTemplate: String,
    val seniAliranQuestionTitleTemplate: String,
    val seniAliranCorrectFeedback: String,
    val seniAliranIncorrectFeedback: String,
    val seniAliranNextQuestion: String,
    val seniAliranBackToList: String,
    val seniAliranAllDoneMessage: String,
)

data class MathGameStrings(
    val mathGameHitungCepat: String,
    val mathGameHots: String,
    val mathGameLogika: String,
    val mathGameTekaTeki: String,
    val mathGamePuzzle: String,
)

data class SpeedMathStrings(
    val speedMathDescription: String,
    val speedMathStartButton: String,
    val speedMathBestScoreTemplate: String,
    val speedMathScoreTemplate: String,
    val speedMathGameOverTitle: String,
    val speedMathNewHighScore: String,
    val speedMathFinalScoreTemplate: String,
    val speedMathAverageTimeTemplate: String,
    val speedMathPlayAgain: String,
)

data class HotsStrings(
    val hotsDescription: String,
    val hotsScoreTemplate: String,
    val hotsQuestionTitleTemplate: String,
    val hotsAnswerLabel: String,
    val hotsCheckAnswerButton: String,
    val hotsCorrectFeedback: String,
    val hotsIncorrectFeedbackTemplate: String,
    val hotsNextQuestion: String,
    val hotsBackToList: String,
    val hotsAllDoneMessage: String,
)

data class LogikaStrings(
    val logikaDescription: String,
    val logikaScoreTemplate: String,
    val logikaPuzzleTitleTemplate: String,
    val logikaCorrectFeedback: String,
    val logikaIncorrectFeedback: String,
    val logikaNextPuzzle: String,
    val logikaBackToList: String,
    val logikaAllDoneMessage: String,
    val logikaChooseNextLabel: String,
    val logikaChooseOddLabel: String,
)

data class TekaTekiStrings(
    val tekaTekiDescription: String,
    val tekaTekiScoreTemplate: String,
    val tekaTekiQuestionTitleTemplate: String,
    val tekaTekiAnswerLabel: String,
    val tekaTekiCheckAnswerButton: String,
    val tekaTekiCorrectFeedback: String,
    val tekaTekiIncorrectFeedbackTemplate: String,
    val tekaTekiNextQuestion: String,
    val tekaTekiBackToList: String,
    val tekaTekiAllDoneMessage: String,
    val tekaTekiShowHintButton: String,
)

data class PuzzleStrings(
    val puzzleDescription: String,
    val puzzleMovesTemplate: String,
    val puzzleTimeTemplate: String,
    val puzzleBestMovesTemplate: String,
    val puzzleNoBestYet: String,
    val puzzleSolvedTitle: String,
    val puzzleNewBestMessage: String,
    val puzzleResultTemplate: String,
    val puzzlePlayAgain: String,
    val puzzleShuffleContentDesc: String,
)

data class LifeOSStrings(
    val localeTag: String,
    val nav: NavStrings,
    val lainnya: LainnyaStrings,
    val settings: SettingsStrings,
    val shared: SharedStrings,
    val beranda: BerandaStrings,
    val notes: NotesStrings,
    val noteEditor: NoteEditorStrings,
    val habit: HabitStrings,
    val habitReminder: HabitReminderStrings,
    val habitSummary: HabitSummaryStrings,
    val pomodoro: PomodoroStrings,
    val pomodoroSummary: PomodoroSummaryStrings,
    val drawing: DrawingStrings,
    val money: MoneyStrings,
    val savings: SavingsStrings,
    val jadwal: JadwalStrings,
    val targetHidup: TargetHidupStrings,
    val statistik: StatistikStrings,
    val aiAssistant: AiAssistantStrings,
    val belajar: BelajarStrings,
    val bahasaInggrisGame: BahasaInggrisGameStrings,
    val kosakata: KosakataStrings,
    val tataBahasa: TataBahasaStrings,
    val susunKalimat: SusunKalimatStrings,
    val listening: ListeningStrings,
    val fisikaGame: FisikaGameStrings,
    val fisikaBesaran: FisikaBesaranStrings,
    val fisikaGerak: FisikaGerakStrings,
    val fisikaEnergi: FisikaEnergiStrings,
    val fisikaListrik: FisikaListrikStrings,
    val kimiaGame: KimiaGameStrings,
    val kimiaAtom: KimiaAtomStrings,
    val kimiaIkatan: KimiaIkatanStrings,
    val kimiaAsamBasa: KimiaAsamBasaStrings,
    val kimiaWujud: KimiaWujudStrings,
    val musikGame: MusikGameStrings,
    val musikNotNada: MusikNotNadaStrings,
    val musikRitme: MusikRitmeStrings,
    val musikAlat: MusikAlatStrings,
    val musikTeori: MusikTeoriStrings,
    val seniGame: SeniGameStrings,
    val seniWarna: SeniWarnaStrings,
    val seniUnsur: SeniUnsurStrings,
    val seniTeknik: SeniTeknikStrings,
    val seniAliran: SeniAliranStrings,
    val mathGame: MathGameStrings,
    val speedMath: SpeedMathStrings,
    val hots: HotsStrings,
    val logika: LogikaStrings,
    val tekaTeki: TekaTekiStrings,
    val puzzle: PuzzleStrings,
)

val IndonesianStrings = LifeOSStrings(
    localeTag = "id-ID",
    nav = NavStrings(
        navBeranda = "Beranda",
        navNotes = "Notes",
        navHabit = "Habit",
        navPomodoro = "Pomodoro",
        navLainnya = "Lainnya",
    ),
    lainnya = LainnyaStrings(
        lainnyaTitle = "Lainnya",
        comingSoon = "Segera hadir",
        moduleMoneyManager = "Money Manager",
        moduleBelajar = "Belajar (Beta)",
        moduleJadwal = "Jadwal",
        moduleTargetHidup = "Target Hidup",
        moduleAiAssistant = "AI Assistant",
        moduleMoodTracker = "Mood Tracker",
        moduleCloudSync = "Cloud Sync",
        moduleDashboardStatistik = "Dashboard Statistik",
        moduleSettings = "Pengaturan",
    ),
    settings = SettingsStrings(
        settingsTitle = "Pengaturan",
        settingsThemeSection = "Tema",
        settingsThemeLight = "Terang",
        settingsThemeDark = "Gelap",
        settingsThemeSystem = "Ikuti sistem",
        settingsLanguageSection = "Bahasa",
        settingsLanguageIndonesian = "Indonesia",
        settingsLanguageEnglish = "English",
        settingsAboutSection = "Tentang Aplikasi",
        settingsAboutDescription = "LifeOS adalah sistem operasi kehidupan pribadi: catatan, habit tracker, dan pomodoro dalam satu aplikasi.",
        settingsAboutVersion = "Versi 1.0",
        settingsAboutTagline = "Dirancang untuk membantumu mengambil kendali penuh atas hidup — satu kebiasaan baik, satu fokus, satu hari pada satu waktu.",
        settingsAboutCreatorLabel = "Diciptakan oleh",
        settingsAboutCreatorName = "LEGALATION — Samuel Manik",
        settingsDataSection = "Kelola Data",
        settingsClearDataButton = "Hapus Semua Data",
        settingsClearDataConfirmTitle = "Hapus semua data?",
        settingsClearDataConfirmText = "Semua catatan, habit, dan riwayat pomodoro akan dihapus permanen. Tindakan ini tidak bisa dibatalkan.",
        settingsClearDataConfirm = "Hapus",
        settingsClearDataCancel = "Batal",
        settingsClearDataDone = "Semua data berhasil dihapus",
        settingsPomodoroSection = "Durasi Pomodoro",
        settingsPomodoroFocusLabel = "Fokus",
        settingsPomodoroShortBreakLabel = "Istirahat Pendek",
        settingsPomodoroLongBreakLabel = "Istirahat Panjang",
        settingsMinutesTemplate = "%1\$d menit",
        settingsDecreaseContentDesc = "Kurangi",
        settingsIncreaseContentDesc = "Tambah",
    ),
    shared = SharedStrings(
        untitledNote = "(Tanpa judul)",
        back = "Kembali",
        cancel = "Batal",
        delete = "Hapus",
        save = "Simpan",
    ),
    beranda = BerandaStrings(
        berandaGreetingMorning = "Selamat pagi!",
        berandaGreetingAfternoon = "Selamat siang!",
        berandaGreetingEvening = "Selamat sore!",
        berandaGreetingNight = "Selamat malam!",
        berandaSubtitle = "Ini ringkasan LifeOS kamu hari ini.",
        berandaHabitCardTitle = "Habit hari ini",
        berandaHabitProgressTemplate = "%1\$d dari %2\$d selesai",
        berandaStatNotesLabel = "Notes",
        berandaStatNotesValueTemplate = "%1\$d catatan",
        berandaStatPomodoroLabel = "Pomodoro",
        berandaStatPomodoroValueTemplate = "%1\$d sesi hari ini",
        berandaActivitiesTitle = "Aktivitas",
        berandaHabitActivityEmpty = "Belum ada habit dibuat",
        berandaHabitActivityTemplate = "%1\$d dari %2\$d habit selesai hari ini",
        berandaNotesActivityEmpty = "Belum ada catatan",
        berandaNotesActivityTemplate = "Catatan terbaru: %1\$s",
        berandaPomodoroActivityEmpty = "Belum ada sesi pomodoro hari ini",
        berandaPomodoroActivityTemplate = "%1\$d sesi fokus selesai hari ini",
        berandaHabitMotivationText = "Habit kecil, dampak besar — tetap bergerak tiap hari!",
        berandaPomodoroMotivationText = "Fokus 25 menit bisa mengubah harimu!",
    ),
    notes = NotesStrings(
        notesEmptyTitle = "Notes",
        notesEmptySubtitle = "Belum ada catatan, tekan + untuk menambah",
        notesAddContentDesc = "Tambah catatan",
        notesDeleteContentDesc = "Hapus catatan",
        notesDeleteDialogTitle = "Hapus catatan?",
        notesDeleteDialogText = "Catatan yang dihapus tidak bisa dikembalikan.",
        notesChecklistDoneTemplate = "%1\$d/%2\$d selesai",
        notesSearchPlaceholder = "Cari catatan...",
        notesSearchClearContentDesc = "Hapus pencarian",
        notesSearchEmptyTitle = "Tidak ditemukan",
        notesSearchEmptySubtitle = "Tidak ada catatan yang cocok dengan pencarianmu",
        notesPinnedSectionTitle = "Disematkan",
        notesOthersSectionTitle = "Lainnya",
        notesPinContentDesc = "Sematkan catatan",
        notesUnpinContentDesc = "Lepas sematan",
        notesAddChooseTypeTitle = "Buat catatan baru",
        notesAddTypeText = "Catatan Teks",
        notesAddTypeDrawing = "Coretan / Gambar",
        notesDrawingLabel = "Coretan",
    ),
    noteEditor = NoteEditorStrings(
        noteEditorTitleEditing = "Edit Catatan",
        noteEditorTitleNew = "Catatan Baru",
        noteEditorDeleteContentDesc = "Hapus catatan",
        noteEditorSaveContentDesc = "Simpan catatan",
        noteEditorTitleLabel = "Judul",
        noteEditorContentLabel = "Isi catatan",
        noteEditorChecklistHeader = "Checklist kegiatan",
        noteEditorChecklistPlaceholder = "Nama kegiatan",
        noteEditorChecklistRemoveContentDesc = "Hapus kegiatan",
        noteEditorAddChecklistItem = "Tambah kegiatan",
        noteEditorColorLabel = "Warna catatan",
        noteEditorColorDefaultContentDesc = "Tanpa warna",
        noteEditorColorCustomContentDesc = "Warna kustom",
        noteEditorCustomColorTitle = "Pilih warna kustom",
        noteEditorCustomColorConfirm = "Pilih",
        noteEditorCustomColorRed = "Merah",
        noteEditorCustomColorGreen = "Hijau",
        noteEditorCustomColorBlue = "Biru",
    ),
    habit = HabitStrings(
        habitTitle = "Habit Tracker",
        habitEmptySubtitle = "Belum ada habit, tekan + untuk menambah",
        habitAddContentDesc = "Tambah habit",
        habitSummaryContentDesc = "Ringkasan habit",
        habitAddDialogTitle = "Tambah Habit",
        habitNameLabel = "Nama habit",
        habitAdd = "Tambah",
        habitDeleteContentDesc = "Hapus habit",
        habitDeleteDialogTitle = "Hapus habit?",
        habitDeleteDialogText = "Riwayat dan streak habit ini akan hilang.",
        habitStreakTemplate = "%1\$d hari beruntun",
    ),
    habitReminder = HabitReminderStrings(
        habitReminderNoneLabel = "Tanpa pengingat",
        habitReminderSetContentDesc = "Atur jam pengingat",
        habitReminderDialogTitle = "Atur jam pengingat",
        habitReminderClear = "Hapus pengingat",
        habitReminderNotificationTitle = "Waktunya habit 🔔",
        habitReminderNotificationTextTemplate = "Saatnya melakukan: %1\$s",
        habitReminderChannelName = "Pengingat Habit",
        habitReminderChannelDescription = "Notifikasi pengingat untuk habit harianmu",
    ),
    habitSummary = HabitSummaryStrings(
        habitSummaryTitle = "Ringkasan Habit",
        habitSummaryDateLabel = "Tanggal",
        habitSummaryEmptyTitle = "Belum ada habit",
        habitSummaryEmptySubtitle = "Tambah habit dulu di tab Habit Tracker",
        habitSummaryDoneTemplate = "%1\$d dari %2\$d selesai",
        habitSummaryPick = "Pilih",
    ),
    pomodoro = PomodoroStrings(
        pomodoroTitle = "Pomodoro",
        pomodoroPhaseFocus = "Fokus",
        pomodoroPhaseShortBreak = "Istirahat Pendek",
        pomodoroPhaseLongBreak = "Istirahat Panjang",
        pomodoroResetContentDesc = "Reset",
        pomodoroPauseContentDesc = "Jeda",
        pomodoroStartContentDesc = "Mulai",
        pomodoroSkipContentDesc = "Lewati",
        pomodoroSessionsTodayTemplate = "%1\$d sesi fokus selesai hari ini",
        pomodoroHelpContentDesc = "Apa itu Pomodoro?",
        pomodoroHelpTitle = "Apa itu Pomodoro?",
        pomodoroHelpText = "Teknik fokus kerja/belajar: 25 menit fokus penuh, lalu istirahat " +
            "5 menit. Ulangi 4 kali, setelah itu dapat istirahat panjang 15 menit " +
            "dan siklusnya mulai lagi dari awal.\n\n" +
            "4 titik di bawah timer menunjukkan progress siklusmu hari ini. " +
            "Tekan tombol tengah untuk mulai/jeda, ikon reset untuk mengulang " +
            "fase saat ini, dan ikon lewati kalau mau langsung pindah fase.",
        pomodoroHelpConfirm = "Mengerti",
        pomodoroHistoryContentDesc = "Riwayat sesi",
    ),
    pomodoroSummary = PomodoroSummaryStrings(
        pomodoroSummaryTitle = "Riwayat Pomodoro",
        pomodoroSummaryDateLabel = "Tanggal",
        pomodoroSummaryEmptyTitle = "Belum ada sesi",
        pomodoroSummaryEmptySubtitle = "Tidak ada sesi fokus yang selesai pada tanggal ini",
        pomodoroSummaryCountTemplate = "%1\$d sesi fokus selesai",
        pomodoroSummarySessionTimeTemplate = "Selesai pukul %1\$s",
    ),
    drawing = DrawingStrings(
        drawingEditorTitleNew = "Coretan Baru",
        drawingEditorTitleEditing = "Edit Coretan",
        drawingUndoContentDesc = "Urungkan",
        drawingClearContentDesc = "Hapus semua coretan",
        drawingClearConfirmTitle = "Hapus semua coretan?",
        drawingClearConfirmText = "Semua goresan di kanvas ini akan dihapus. Tindakan ini tidak bisa dibatalkan.",
        drawingTitlePlaceholder = "Judul (opsional)",
    ),
    money = MoneyStrings(
        moneySummaryIncome = "Pemasukan",
        moneySummaryExpense = "Pengeluaran",
        moneySummaryBalance = "Saldo",
        moneyEmptyTitle = "Belum ada transaksi",
        moneyEmptySubtitle = "Tekan + untuk mencatat pemasukan atau pengeluaran",
        moneyAddContentDesc = "Tambah transaksi",
        moneyDeleteDialogTitle = "Hapus transaksi?",
        moneyDeleteDialogText = "Transaksi yang dihapus tidak bisa dikembalikan.",
        moneyAddTransactionTitle = "Tambah Transaksi",
        moneyAmountLabel = "Jumlah",
        moneyCategoryLabel = "Kategori",
        moneyDateLabel = "Tanggal",
        moneyNoteLabel = "Catatan",
        moneyNotePlaceholder = "Catatan (opsional)",
        moneyCategoryFood = "Makanan",
        moneyCategoryTransport = "Transport",
        moneyCategoryHousing = "Kos",
        moneyCategoryEntertainment = "Hiburan",
        moneyCategoryShopping = "Belanja",
        moneyCategoryHealth = "Kesehatan",
        moneyCategoryOtherExpense = "Lainnya",
        moneyCategoryAllowance = "Uang Saku",
        moneyCategorySalary = "Gaji",
        moneyCategoryBonus = "Bonus",
        moneyCategoryOtherIncome = "Lainnya",
        moneyTabTransactions = "Transaksi",
        moneyTabSavings = "Tabungan",
        moneyTabInsights = "Ringkasan",
        moneyStreakTemplate = "%1\$d hari berturut-turut mencatat",
        moneyStreakEmpty = "Mulai catat transaksi hari ini untuk membangun streak!",
        moneyInsightTopCategoryTemplate = "Pengeluaran terbesar bulan ini: %1\$s (%2\$s)",
        moneyInsightNoDataYet = "Catat transaksi untuk melihat ringkasan bulan ini",
        moneyInsightVsLastMonthUpTemplate = "Naik %1\$d%% dibanding bulan lalu",
        moneyInsightVsLastMonthDownTemplate = "Turun %1\$d%% dibanding bulan lalu",
        moneyBreakdownTitle = "Pengeluaran per Kategori (Bulan Ini)",
        moneyBreakdownEmpty = "Belum ada pengeluaran bulan ini",
        moneyBudgetSectionTitle = "Budget Bulanan",
        moneyBudgetPercentTemplate = "%1\$s dari %2\$s (%3\$d%%)",
        moneyBudgetOverTemplate = "Lewat %1\$s dari batas!",
        moneyAddBudgetLabel = "Tambah budget kategori",
        moneySetBudgetTitle = "Atur Budget",
        moneyBudgetLimitLabel = "Batas per bulan",
        moneyDeleteBudgetContentDesc = "Hapus budget",
        moneyNoBudgetsYet = "Belum ada budget yang diatur",
    ),
    savings = SavingsStrings(
        savingsEmptyTitle = "Belum ada target tabungan",
        savingsEmptySubtitle = "Tekan + untuk membuat target tabungan atau investasi",
        savingsAddContentDesc = "Tambah target",
        savingsAddGoalTitle = "Target Baru",
        savingsGoalNameLabel = "Nama target",
        savingsTargetAmountLabel = "Jumlah target",
        savingsMonthlyContributionLabel = "Nabung per bulan",
        savingsAnnualReturnLabel = "Bunga/imbal hasil per tahun (%)",
        savingsAnnualReturnHint = "Opsional, isi 0 untuk tabungan biasa tanpa bunga",
        savingsEstimateLabel = "Perkiraan waktu tercapai",
        savingsEstimateAchieved = "Target sudah tercapai!",
        savingsEstimateMonthsTemplate = "Sekitar %1\$d bulan lagi",
        savingsEstimateYearsMonthsTemplate = "Sekitar %1\$d tahun %2\$d bulan lagi",
        savingsEstimateNeverTemplate = "Tidak akan tercapai dengan setoran saat ini",
        savingsProgressTemplate = "%1\$s dari %2\$s",
        savingsDeleteGoalContentDesc = "Hapus target",
        savingsDeleteGoalDialogTitle = "Hapus target ini?",
        savingsDeleteGoalDialogText = "Seluruh riwayat setoran target ini akan ikut terhapus permanen.",
        savingsAddDepositContentDesc = "Tambah setoran",
        savingsAddDepositTitle = "Tambah Setoran",
        savingsDepositAmountLabel = "Jumlah setoran",
        savingsDepositHistoryTitle = "Riwayat Setoran",
        savingsNoDepositsYet = "Belum ada setoran",
        savingsDeleteDepositDialogTitle = "Hapus setoran ini?",
        savingsDeleteDepositDialogText = "Jumlah setoran akan dikurangi dari progress target.",
    ),
    jadwal = JadwalStrings(
        jadwalTitle = "Jadwal",
        jadwalEmptySubtitle = "Belum ada jadwal, tekan + untuk menambah",
        jadwalAddContentDesc = "Tambah jadwal",
        jadwalAddDialogTitle = "Tambah Jadwal",
        jadwalTitleLabel = "Judul kegiatan",
        jadwalDateLabel = "Tanggal",
        jadwalTimeLabel = "Waktu",
        jadwalTimeNoneLabel = "Tanpa waktu tertentu",
        jadwalTimeDialogTitle = "Atur waktu jadwal",
        jadwalClearTime = "Hapus waktu",
        jadwalAdd = "Tambah",
        jadwalDeleteContentDesc = "Hapus jadwal",
        jadwalDeleteDialogTitle = "Hapus jadwal ini?",
        jadwalDeleteDialogText = "Jadwal yang dihapus tidak bisa dikembalikan.",
        jadwalReminderChannelName = "Pengingat Jadwal",
        jadwalReminderChannelDescription = "Notifikasi saat jadwal yang kamu atur sudah waktunya",
        jadwalReminderNotificationTitle = "Waktunya jadwal! ⏰",
        jadwalReminderNotificationTextTemplate = "Saatnya: %1\$s",
    ),
    targetHidup = TargetHidupStrings(
        targetHidupTitle = "Target Hidup",
        targetHidupEmptySubtitle = "Belum ada target, tekan + untuk menambah",
        targetHidupAddContentDesc = "Tambah target",
        targetHidupAddDialogTitle = "Tambah Target Hidup",
        targetHidupTitleLabel = "Nama target",
        targetHidupTargetDateLabel = "Target tanggal",
        targetHidupTargetDateNoneLabel = "Tanpa batas waktu",
        targetHidupProgressLabel = "Progress",
        targetHidupProgressTemplate = "%1\$d%% tercapai",
        targetHidupAdd = "Tambah",
        targetHidupEditDialogTitle = "Update Progress",
        targetHidupDeleteContentDesc = "Hapus target",
        targetHidupDeleteDialogTitle = "Hapus target ini?",
        targetHidupDeleteDialogText = "Target yang dihapus tidak bisa dikembalikan.",
        targetHidupCompletedLabel = "Tercapai! 🎉",
        targetHidupDaysLeftTemplate = "%1\$d hari lagi",
        targetHidupOverdueLabel = "Lewat tenggat",
    ),
    statistik = StatistikStrings(
        statistikTitle = "Dashboard Statistik",
        statistikTotalNotes = "Total Catatan",
        statistikTotalPomodoro = "Total Sesi Pomodoro",
        statistikActiveHabits = "Habit Aktif",
        statistikLongestStreak = "Rekor Streak",
        statistikStreakTemplate = "%1\$d hari",
        statistikGoalsAchieved = "Target Tercapai",
        statistikPomodoroChartTitle = "Sesi Pomodoro (7 Hari Terakhir)",
        statistikHabitChartTitle = "Penyelesaian Habit Hari Ini",
        statistikTodayLabel = "Hari ini",
        statistikDonutCompletedLabel = "Selesai",
        statistikDonutRemainingLabel = "Belum",
        statistikDonutTodayTemplate = "%1\$d dari %2\$d habit selesai hari ini",
        statistikDonutAvgTemplate = "Rata-rata 7 hari: %1\$d%%",
    ),
    aiAssistant = AiAssistantStrings(
        aiAssistantTitle = "AI Assistant",
        aiAssistantEmptySubtitle = "Tanya apa saja — asisten AI ini bisa bantu soal catatan, jadwal, atau sekadar ngobrol.",
        aiAssistantInputPlaceholder = "Ketik pesan...",
        aiAssistantSendContentDesc = "Kirim",
        aiAssistantClearContentDesc = "Hapus obrolan",
        aiAssistantClearDialogTitle = "Hapus semua obrolan?",
        aiAssistantClearDialogText = "Riwayat obrolan dengan AI Assistant akan dihapus permanen.",
        aiAssistantRateLimitMessage = "Batas pesan harian tercapai. Coba lagi besok ya.",
        aiAssistantErrorPrefixTemplate = "Terjadi kesalahan: %1\$s",
        aiAssistantThinkingLabel = "Mengetik...",
    ),
    belajar = BelajarStrings(
        belajarTitle = "Belajar",
        belajarSubjectMatematika = "Matematika",
        belajarSubjectBahasaInggris = "Bahasa Inggris",
        belajarSubjectFisika = "Fisika",
        belajarSubjectKimia = "Kimia",
        belajarSubjectMusik = "Musik",
        belajarSubjectSeni = "Seni",
    ),
    bahasaInggrisGame = BahasaInggrisGameStrings(
        bahasaInggrisGameKosakata = "Kosakata",
        bahasaInggrisGameTataBahasa = "Tata Bahasa",
        bahasaInggrisGameSusunKalimat = "Susun Kalimat",
        bahasaInggrisGameListening = "Listening & Pengucapan",
    ),
    kosakata = KosakataStrings(
        kosakataDescription = "Uji kosakata Bahasa Inggrismu lewat pilihan ganda.",
        kosakataScoreTemplate = "Skor: %1\$d dari %2\$d benar",
        kosakataQuestionTitleTemplate = "Soal %1\$d",
        kosakataCorrectFeedback = "Benar! 🎉",
        kosakataIncorrectFeedback = "Kurang tepat. Jawaban yang benar ditandai hijau.",
        kosakataNextQuestion = "Soal Berikutnya",
        kosakataBackToList = "Kembali ke Daftar Soal",
        kosakataAllDoneMessage = "Semua soal sudah kamu jawab dengan benar! 🎉",
    ),
    tataBahasa = TataBahasaStrings(
        tataBahasaDescription = "Latih tata bahasa Inggrismu dengan melengkapi kalimat.",
        tataBahasaScoreTemplate = "Skor: %1\$d dari %2\$d benar",
        tataBahasaQuestionTitleTemplate = "Soal %1\$d",
        tataBahasaCorrectFeedback = "Benar! 🎉",
        tataBahasaIncorrectFeedback = "Kurang tepat. Jawaban yang benar ditandai hijau.",
        tataBahasaNextQuestion = "Soal Berikutnya",
        tataBahasaBackToList = "Kembali ke Daftar Soal",
        tataBahasaAllDoneMessage = "Semua soal sudah kamu jawab dengan benar! 🎉",
    ),
    susunKalimat = SusunKalimatStrings(
        susunKalimatDescription = "Susun kata-kata acak menjadi kalimat Bahasa Inggris yang benar.",
        susunKalimatScoreTemplate = "Skor: %1\$d dari %2\$d benar",
        susunKalimatQuestionTitleTemplate = "Kalimat %1\$d",
        susunKalimatCorrectFeedback = "Benar! 🎉",
        susunKalimatIncorrectFeedback = "Kurang tepat. Susunan yang benar:",
        susunKalimatNextQuestion = "Kalimat Berikutnya",
        susunKalimatBackToList = "Kembali ke Daftar Kalimat",
        susunKalimatAllDoneMessage = "Semua kalimat sudah kamu susun dengan benar! 🎉",
        susunKalimatCheckButton = "Periksa Jawaban",
        susunKalimatResetButton = "Ulangi",
        susunKalimatHintLabel = "Petunjuk (Bahasa Indonesia):",
    ),
    listening = ListeningStrings(
        listeningDescription = "Dengarkan kata atau frasa dalam Bahasa Inggris, lalu pilih ejaan yang tepat.",
        listeningScoreTemplate = "Skor: %1\$d dari %2\$d benar",
        listeningQuestionTitleTemplate = "Soal %1\$d",
        listeningCorrectFeedback = "Benar! 🎉",
        listeningIncorrectFeedback = "Kurang tepat. Jawaban yang benar ditandai hijau.",
        listeningNextQuestion = "Soal Berikutnya",
        listeningBackToList = "Kembali ke Daftar Soal",
        listeningAllDoneMessage = "Semua soal sudah kamu jawab dengan benar! 🎉",
        listeningPlayButton = "Putar Suara",
        listeningPrompt = "Dengarkan lalu pilih ejaan yang tepat:",
    ),
    fisikaGame = FisikaGameStrings(
        fisikaGameBesaran = "Besaran & Satuan",
        fisikaGameGerak = "Gerak & Gaya",
        fisikaGameEnergi = "Energi & Usaha",
        fisikaGameListrik = "Listrik & Magnet",
    ),
    fisikaBesaran = FisikaBesaranStrings(
        fisikaBesaranDescription = "Uji pemahamanmu tentang besaran, satuan, dan alat ukur dalam Fisika.",
        fisikaBesaranScoreTemplate = "Skor: %1\$d dari %2\$d benar",
        fisikaBesaranQuestionTitleTemplate = "Soal %1\$d",
        fisikaBesaranCorrectFeedback = "Benar! 🎉",
        fisikaBesaranIncorrectFeedback = "Kurang tepat. Jawaban yang benar ditandai hijau.",
        fisikaBesaranNextQuestion = "Soal Berikutnya",
        fisikaBesaranBackToList = "Kembali ke Daftar Soal",
        fisikaBesaranAllDoneMessage = "Semua soal sudah kamu jawab dengan benar! 🎉",
    ),
    fisikaGerak = FisikaGerakStrings(
        fisikaGerakDescription = "Latih konsep gerak, kecepatan, gaya, dan Hukum Newton.",
        fisikaGerakScoreTemplate = "Skor: %1\$d dari %2\$d benar",
        fisikaGerakQuestionTitleTemplate = "Soal %1\$d",
        fisikaGerakCorrectFeedback = "Benar! 🎉",
        fisikaGerakIncorrectFeedback = "Kurang tepat. Jawaban yang benar ditandai hijau.",
        fisikaGerakNextQuestion = "Soal Berikutnya",
        fisikaGerakBackToList = "Kembali ke Daftar Soal",
        fisikaGerakAllDoneMessage = "Semua soal sudah kamu jawab dengan benar! 🎉",
    ),
    fisikaEnergi = FisikaEnergiStrings(
        fisikaEnergiDescription = "Pahami konsep usaha, energi, dan daya lewat soal pilihan ganda.",
        fisikaEnergiScoreTemplate = "Skor: %1\$d dari %2\$d benar",
        fisikaEnergiQuestionTitleTemplate = "Soal %1\$d",
        fisikaEnergiCorrectFeedback = "Benar! 🎉",
        fisikaEnergiIncorrectFeedback = "Kurang tepat. Jawaban yang benar ditandai hijau.",
        fisikaEnergiNextQuestion = "Soal Berikutnya",
        fisikaEnergiBackToList = "Kembali ke Daftar Soal",
        fisikaEnergiAllDoneMessage = "Semua soal sudah kamu jawab dengan benar! 🎉",
    ),
    fisikaListrik = FisikaListrikStrings(
        fisikaListrikDescription = "Uji pengetahuanmu tentang listrik, arus, tegangan, hambatan, dan magnet.",
        fisikaListrikScoreTemplate = "Skor: %1\$d dari %2\$d benar",
        fisikaListrikQuestionTitleTemplate = "Soal %1\$d",
        fisikaListrikCorrectFeedback = "Benar! 🎉",
        fisikaListrikIncorrectFeedback = "Kurang tepat. Jawaban yang benar ditandai hijau.",
        fisikaListrikNextQuestion = "Soal Berikutnya",
        fisikaListrikBackToList = "Kembali ke Daftar Soal",
        fisikaListrikAllDoneMessage = "Semua soal sudah kamu jawab dengan benar! 🎉",
    ),
    kimiaGame = KimiaGameStrings(
        kimiaGameAtom = "Atom & Unsur",
        kimiaGameIkatan = "Ikatan & Reaksi",
        kimiaGameAsamBasa = "Asam & Basa",
        kimiaGameWujud = "Wujud & Campuran",
    ),
    kimiaAtom = KimiaAtomStrings(
        kimiaAtomDescription = "Pelajari struktur atom, partikel penyusun, lambang unsur, dan tabel periodik.",
        kimiaAtomScoreTemplate = "Skor: %1\$d dari %2\$d benar",
        kimiaAtomQuestionTitleTemplate = "Soal %1\$d",
        kimiaAtomCorrectFeedback = "Benar! 🎉",
        kimiaAtomIncorrectFeedback = "Kurang tepat. Jawaban yang benar ditandai hijau.",
        kimiaAtomNextQuestion = "Soal Berikutnya",
        kimiaAtomBackToList = "Kembali ke Daftar Soal",
        kimiaAtomAllDoneMessage = "Semua soal sudah kamu jawab dengan benar! 🎉",
    ),
    kimiaIkatan = KimiaIkatanStrings(
        kimiaIkatanDescription = "Uji pemahamanmu tentang ikatan kimia, rumus senyawa, dan reaksi kimia.",
        kimiaIkatanScoreTemplate = "Skor: %1\$d dari %2\$d benar",
        kimiaIkatanQuestionTitleTemplate = "Soal %1\$d",
        kimiaIkatanCorrectFeedback = "Benar! 🎉",
        kimiaIkatanIncorrectFeedback = "Kurang tepat. Jawaban yang benar ditandai hijau.",
        kimiaIkatanNextQuestion = "Soal Berikutnya",
        kimiaIkatanBackToList = "Kembali ke Daftar Soal",
        kimiaIkatanAllDoneMessage = "Semua soal sudah kamu jawab dengan benar! 🎉",
    ),
    kimiaAsamBasa = KimiaAsamBasaStrings(
        kimiaAsamBasaDescription = "Kenali sifat asam, basa, netral, nilai pH, dan indikator.",
        kimiaAsamBasaScoreTemplate = "Skor: %1\$d dari %2\$d benar",
        kimiaAsamBasaQuestionTitleTemplate = "Soal %1\$d",
        kimiaAsamBasaCorrectFeedback = "Benar! 🎉",
        kimiaAsamBasaIncorrectFeedback = "Kurang tepat. Jawaban yang benar ditandai hijau.",
        kimiaAsamBasaNextQuestion = "Soal Berikutnya",
        kimiaAsamBasaBackToList = "Kembali ke Daftar Soal",
        kimiaAsamBasaAllDoneMessage = "Semua soal sudah kamu jawab dengan benar! 🎉",
    ),
    kimiaWujud = KimiaWujudStrings(
        kimiaWujudDescription = "Pahami perubahan wujud zat serta campuran homogen dan heterogen.",
        kimiaWujudScoreTemplate = "Skor: %1\$d dari %2\$d benar",
        kimiaWujudQuestionTitleTemplate = "Soal %1\$d",
        kimiaWujudCorrectFeedback = "Benar! 🎉",
        kimiaWujudIncorrectFeedback = "Kurang tepat. Jawaban yang benar ditandai hijau.",
        kimiaWujudNextQuestion = "Soal Berikutnya",
        kimiaWujudBackToList = "Kembali ke Daftar Soal",
        kimiaWujudAllDoneMessage = "Semua soal sudah kamu jawab dengan benar! 🎉",
    ),
    musikGame = MusikGameStrings(
        musikGameNotNada = "Not & Nada",
        musikGameRitme = "Ritme & Tempo",
        musikGameAlat = "Alat Musik",
        musikGameTeori = "Teori Musik",
    ),
    musikNotNada = MusikNotNadaStrings(
        musikNotNadaDescription = "Kenali tangga nada, notasi, nada, dan tanda-tanda dalam musik.",
        musikNotNadaScoreTemplate = "Skor: %1\$d dari %2\$d benar",
        musikNotNadaQuestionTitleTemplate = "Soal %1\$d",
        musikNotNadaCorrectFeedback = "Benar! 🎉",
        musikNotNadaIncorrectFeedback = "Kurang tepat. Jawaban yang benar ditandai hijau.",
        musikNotNadaNextQuestion = "Soal Berikutnya",
        musikNotNadaBackToList = "Kembali ke Daftar Soal",
        musikNotNadaAllDoneMessage = "Semua soal sudah kamu jawab dengan benar! 🎉",
    ),
    musikRitme = MusikRitmeStrings(
        musikRitmeDescription = "Pelajari tempo, birama, ketukan, dan istilah ritme dalam musik.",
        musikRitmeScoreTemplate = "Skor: %1\$d dari %2\$d benar",
        musikRitmeQuestionTitleTemplate = "Soal %1\$d",
        musikRitmeCorrectFeedback = "Benar! 🎉",
        musikRitmeIncorrectFeedback = "Kurang tepat. Jawaban yang benar ditandai hijau.",
        musikRitmeNextQuestion = "Soal Berikutnya",
        musikRitmeBackToList = "Kembali ke Daftar Soal",
        musikRitmeAllDoneMessage = "Semua soal sudah kamu jawab dengan benar! 🎉",
    ),
    musikAlat = MusikAlatStrings(
        musikAlatDescription = "Uji pengetahuanmu tentang alat musik dan cara memainkannya.",
        musikAlatScoreTemplate = "Skor: %1\$d dari %2\$d benar",
        musikAlatQuestionTitleTemplate = "Soal %1\$d",
        musikAlatCorrectFeedback = "Benar! 🎉",
        musikAlatIncorrectFeedback = "Kurang tepat. Jawaban yang benar ditandai hijau.",
        musikAlatNextQuestion = "Soal Berikutnya",
        musikAlatBackToList = "Kembali ke Daftar Soal",
        musikAlatAllDoneMessage = "Semua soal sudah kamu jawab dengan benar! 🎉",
    ),
    musikTeori = MusikTeoriStrings(
        musikTeoriDescription = "Pahami melodi, harmoni, akor, dinamika, dan warna suara.",
        musikTeoriScoreTemplate = "Skor: %1\$d dari %2\$d benar",
        musikTeoriQuestionTitleTemplate = "Soal %1\$d",
        musikTeoriCorrectFeedback = "Benar! 🎉",
        musikTeoriIncorrectFeedback = "Kurang tepat. Jawaban yang benar ditandai hijau.",
        musikTeoriNextQuestion = "Soal Berikutnya",
        musikTeoriBackToList = "Kembali ke Daftar Soal",
        musikTeoriAllDoneMessage = "Semua soal sudah kamu jawab dengan benar! 🎉",
    ),
    seniGame = SeniGameStrings(
        seniGameWarna = "Warna",
        seniGameUnsur = "Unsur Seni Rupa",
        seniGameTeknik = "Teknik & Media",
        seniGameAliran = "Aliran & Tokoh",
    ),
    seniWarna = SeniWarnaStrings(
        seniWarnaDescription = "Pelajari warna primer, sekunder, warna hangat/sejuk, dan lingkaran warna.",
        seniWarnaScoreTemplate = "Skor: %1\$d dari %2\$d benar",
        seniWarnaQuestionTitleTemplate = "Soal %1\$d",
        seniWarnaCorrectFeedback = "Benar! 🎉",
        seniWarnaIncorrectFeedback = "Kurang tepat. Jawaban yang benar ditandai hijau.",
        seniWarnaNextQuestion = "Soal Berikutnya",
        seniWarnaBackToList = "Kembali ke Daftar Soal",
        seniWarnaAllDoneMessage = "Semua soal sudah kamu jawab dengan benar! 🎉",
    ),
    seniUnsur = SeniUnsurStrings(
        seniUnsurDescription = "Kenali unsur-unsur seni rupa: titik, garis, bidang, tekstur, dan ruang.",
        seniUnsurScoreTemplate = "Skor: %1\$d dari %2\$d benar",
        seniUnsurQuestionTitleTemplate = "Soal %1\$d",
        seniUnsurCorrectFeedback = "Benar! 🎉",
        seniUnsurIncorrectFeedback = "Kurang tepat. Jawaban yang benar ditandai hijau.",
        seniUnsurNextQuestion = "Soal Berikutnya",
        seniUnsurBackToList = "Kembali ke Daftar Soal",
        seniUnsurAllDoneMessage = "Semua soal sudah kamu jawab dengan benar! 🎉",
    ),
    seniTeknik = SeniTeknikStrings(
        seniTeknikDescription = "Uji pengetahuanmu tentang teknik dan media berkarya seni rupa.",
        seniTeknikScoreTemplate = "Skor: %1\$d dari %2\$d benar",
        seniTeknikQuestionTitleTemplate = "Soal %1\$d",
        seniTeknikCorrectFeedback = "Benar! 🎉",
        seniTeknikIncorrectFeedback = "Kurang tepat. Jawaban yang benar ditandai hijau.",
        seniTeknikNextQuestion = "Soal Berikutnya",
        seniTeknikBackToList = "Kembali ke Daftar Soal",
        seniTeknikAllDoneMessage = "Semua soal sudah kamu jawab dengan benar! 🎉",
    ),
    seniAliran = SeniAliranStrings(
        seniAliranDescription = "Kenali aliran seni lukis dan tokoh-tokoh pelukis terkenal.",
        seniAliranScoreTemplate = "Skor: %1\$d dari %2\$d benar",
        seniAliranQuestionTitleTemplate = "Soal %1\$d",
        seniAliranCorrectFeedback = "Benar! 🎉",
        seniAliranIncorrectFeedback = "Kurang tepat. Jawaban yang benar ditandai hijau.",
        seniAliranNextQuestion = "Soal Berikutnya",
        seniAliranBackToList = "Kembali ke Daftar Soal",
        seniAliranAllDoneMessage = "Semua soal sudah kamu jawab dengan benar! 🎉",
    ),
    mathGame = MathGameStrings(
        mathGameHitungCepat = "Hitung Cepat",
        mathGameHots = "Soal HOTS",
        mathGameLogika = "Asah Logika",
        mathGameTekaTeki = "Teka-Teki",
        mathGamePuzzle = "Puzzle",
    ),
    speedMath = SpeedMathStrings(
        speedMathDescription = "Jawab secepat mungkin sebelum waktu habis. Tiap soal, waktunya makin sedikit!",
        speedMathStartButton = "Mulai",
        speedMathBestScoreTemplate = "Skor tertinggi: %1\$d",
        speedMathScoreTemplate = "Skor: %1\$d",
        speedMathGameOverTitle = "Game Selesai",
        speedMathNewHighScore = "Rekor baru!",
        speedMathFinalScoreTemplate = "Skor akhir: %1\$d",
        speedMathAverageTimeTemplate = "Rata-rata %1\$s detik per soal",
        speedMathPlayAgain = "Main Lagi",
    ),
    hots = HotsStrings(
        hotsDescription = "Kerjakan di kertas coretan, lalu masukkan jawabanmu di sini.",
        hotsScoreTemplate = "Skor: %1\$d dari %2\$d benar",
        hotsQuestionTitleTemplate = "Soal %1\$d",
        hotsAnswerLabel = "Jawabanmu",
        hotsCheckAnswerButton = "Periksa Jawaban",
        hotsCorrectFeedback = "Benar! 🎉",
        hotsIncorrectFeedbackTemplate = "Kurang tepat. Jawaban yang benar: %1\$s",
        hotsNextQuestion = "Soal Berikutnya",
        hotsBackToList = "Kembali ke Daftar Soal",
        hotsAllDoneMessage = "Semua soal sudah kamu selesaikan dengan benar! 🎉",
    ),
    logika = LogikaStrings(
        logikaDescription = "Asah kemampuan berpikir logismu lewat pola bentuk, teka-teki, dan soal deduksi.",
        logikaScoreTemplate = "Skor: %1\$d dari %2\$d benar",
        logikaPuzzleTitleTemplate = "Soal %1\$d",
        logikaCorrectFeedback = "Benar! 🎉",
        logikaIncorrectFeedback = "Kurang tepat. Jawaban yang benar ditandai hijau.",
        logikaNextPuzzle = "Soal Berikutnya",
        logikaBackToList = "Kembali ke Daftar Soal",
        logikaAllDoneMessage = "Semua soal sudah kamu selesaikan dengan benar! 🎉",
        logikaChooseNextLabel = "Pilih lanjutan yang tepat:",
        logikaChooseOddLabel = "Pilih yang berbeda dari yang lain:",
    ),
    tekaTeki = TekaTekiStrings(
        tekaTekiDescription = "Pecahkan teka-teki klasik ini dengan berpikir kreatif. Kalau buntu, coba lihat petunjuknya!",
        tekaTekiScoreTemplate = "Skor: %1\$d dari %2\$d benar",
        tekaTekiQuestionTitleTemplate = "Teka-Teki %1\$d",
        tekaTekiAnswerLabel = "Jawabanmu",
        tekaTekiCheckAnswerButton = "Periksa Jawaban",
        tekaTekiCorrectFeedback = "Benar! 🎉",
        tekaTekiIncorrectFeedbackTemplate = "Kurang tepat. Jawabannya: %1\$s",
        tekaTekiNextQuestion = "Teka-Teki Berikutnya",
        tekaTekiBackToList = "Kembali ke Daftar Teka-Teki",
        tekaTekiAllDoneMessage = "Semua teka-teki sudah kamu pecahkan! 🎉",
        tekaTekiShowHintButton = "Tampilkan Petunjuk",
    ),
    puzzle = PuzzleStrings(
        puzzleDescription = "Susun ulang angka 1 sampai 15 dengan menggeser kotak ke ruang kosong.",
        puzzleMovesTemplate = "Langkah: %1\$d",
        puzzleTimeTemplate = "Waktu: %1\$s",
        puzzleBestMovesTemplate = "Rekor: %1\$d langkah",
        puzzleNoBestYet = "Belum ada rekor",
        puzzleSolvedTitle = "Selesai! 🎉",
        puzzleNewBestMessage = "Rekor baru!",
        puzzleResultTemplate = "%1\$d langkah dalam %2\$s",
        puzzlePlayAgain = "Acak Lagi",
        puzzleShuffleContentDesc = "Acak ulang",
    ),
)

val EnglishStrings = LifeOSStrings(
    localeTag = "en-US",
    nav = NavStrings(
        navBeranda = "Home",
        navNotes = "Notes",
        navHabit = "Habit",
        navPomodoro = "Pomodoro",
        navLainnya = "More",
    ),
    lainnya = LainnyaStrings(
        lainnyaTitle = "More",
        comingSoon = "Coming soon",
        moduleMoneyManager = "Money Manager",
        moduleBelajar = "Study (Beta)",
        moduleJadwal = "Schedule",
        moduleTargetHidup = "Life Goals",
        moduleAiAssistant = "AI Assistant",
        moduleMoodTracker = "Mood Tracker",
        moduleCloudSync = "Cloud Sync",
        moduleDashboardStatistik = "Stats Dashboard",
        moduleSettings = "Settings",
    ),
    settings = SettingsStrings(
        settingsTitle = "Settings",
        settingsThemeSection = "Theme",
        settingsThemeLight = "Light",
        settingsThemeDark = "Dark",
        settingsThemeSystem = "Follow system",
        settingsLanguageSection = "Language",
        settingsLanguageIndonesian = "Indonesia",
        settingsLanguageEnglish = "English",
        settingsAboutSection = "About",
        settingsAboutDescription = "LifeOS is your personal life operating system: notes, habit tracker, and pomodoro in one app.",
        settingsAboutVersion = "Version 1.0",
        settingsAboutTagline = "Built to help you take full command of your life — one good habit, one focused session, one day at a time.",
        settingsAboutCreatorLabel = "Created by",
        settingsAboutCreatorName = "LEGALATION — Samuel Manik",
        settingsDataSection = "Manage Data",
        settingsClearDataButton = "Clear All Data",
        settingsClearDataConfirmTitle = "Clear all data?",
        settingsClearDataConfirmText = "All notes, habits, and pomodoro history will be permanently deleted. This action cannot be undone.",
        settingsClearDataConfirm = "Clear",
        settingsClearDataCancel = "Cancel",
        settingsClearDataDone = "All data cleared successfully",
        settingsPomodoroSection = "Pomodoro Duration",
        settingsPomodoroFocusLabel = "Focus",
        settingsPomodoroShortBreakLabel = "Short Break",
        settingsPomodoroLongBreakLabel = "Long Break",
        settingsMinutesTemplate = "%1\$d minutes",
        settingsDecreaseContentDesc = "Decrease",
        settingsIncreaseContentDesc = "Increase",
    ),
    shared = SharedStrings(
        untitledNote = "(Untitled)",
        back = "Back",
        cancel = "Cancel",
        delete = "Delete",
        save = "Save",
    ),
    beranda = BerandaStrings(
        berandaGreetingMorning = "Good morning!",
        berandaGreetingAfternoon = "Good afternoon!",
        berandaGreetingEvening = "Good evening!",
        berandaGreetingNight = "Good night!",
        berandaSubtitle = "Here's your LifeOS summary for today.",
        berandaHabitCardTitle = "Today's habits",
        berandaHabitProgressTemplate = "%1\$d of %2\$d done",
        berandaStatNotesLabel = "Notes",
        berandaStatNotesValueTemplate = "%1\$d notes",
        berandaStatPomodoroLabel = "Pomodoro",
        berandaStatPomodoroValueTemplate = "%1\$d sessions today",
        berandaActivitiesTitle = "Activity",
        berandaHabitActivityEmpty = "No habits yet",
        berandaHabitActivityTemplate = "%1\$d of %2\$d habits done today",
        berandaNotesActivityEmpty = "No notes yet",
        berandaNotesActivityTemplate = "Latest note: %1\$s",
        berandaPomodoroActivityEmpty = "No pomodoro sessions today",
        berandaPomodoroActivityTemplate = "%1\$d focus sessions completed today",
        berandaHabitMotivationText = "Small habits, big impact — keep moving every day!",
        berandaPomodoroMotivationText = "25 focused minutes can change your day!",
    ),
    notes = NotesStrings(
        notesEmptyTitle = "Notes",
        notesEmptySubtitle = "No notes yet, tap + to add one",
        notesAddContentDesc = "Add note",
        notesDeleteContentDesc = "Delete note",
        notesDeleteDialogTitle = "Delete note?",
        notesDeleteDialogText = "Deleted notes cannot be recovered.",
        notesChecklistDoneTemplate = "%1\$d/%2\$d done",
        notesSearchPlaceholder = "Search notes...",
        notesSearchClearContentDesc = "Clear search",
        notesSearchEmptyTitle = "No results",
        notesSearchEmptySubtitle = "No notes match your search",
        notesPinnedSectionTitle = "Pinned",
        notesOthersSectionTitle = "Others",
        notesPinContentDesc = "Pin note",
        notesUnpinContentDesc = "Unpin note",
        notesAddChooseTypeTitle = "Create a new note",
        notesAddTypeText = "Text Note",
        notesAddTypeDrawing = "Drawing / Sketch",
        notesDrawingLabel = "Drawing",
    ),
    noteEditor = NoteEditorStrings(
        noteEditorTitleEditing = "Edit Note",
        noteEditorTitleNew = "New Note",
        noteEditorDeleteContentDesc = "Delete note",
        noteEditorSaveContentDesc = "Save note",
        noteEditorTitleLabel = "Title",
        noteEditorContentLabel = "Content",
        noteEditorChecklistHeader = "Checklist",
        noteEditorChecklistPlaceholder = "Task name",
        noteEditorChecklistRemoveContentDesc = "Remove item",
        noteEditorAddChecklistItem = "Add item",
        noteEditorColorLabel = "Note color",
        noteEditorColorDefaultContentDesc = "No color",
        noteEditorColorCustomContentDesc = "Custom color",
        noteEditorCustomColorTitle = "Pick a custom color",
        noteEditorCustomColorConfirm = "Select",
        noteEditorCustomColorRed = "Red",
        noteEditorCustomColorGreen = "Green",
        noteEditorCustomColorBlue = "Blue",
    ),
    habit = HabitStrings(
        habitTitle = "Habit Tracker",
        habitEmptySubtitle = "No habits yet, tap + to add one",
        habitAddContentDesc = "Add habit",
        habitSummaryContentDesc = "Habit summary",
        habitAddDialogTitle = "Add Habit",
        habitNameLabel = "Habit name",
        habitAdd = "Add",
        habitDeleteContentDesc = "Delete habit",
        habitDeleteDialogTitle = "Delete habit?",
        habitDeleteDialogText = "This habit's history and streak will be lost.",
        habitStreakTemplate = "%1\$d day streak",
    ),
    habitReminder = HabitReminderStrings(
        habitReminderNoneLabel = "No reminder",
        habitReminderSetContentDesc = "Set reminder time",
        habitReminderDialogTitle = "Set reminder time",
        habitReminderClear = "Remove reminder",
        habitReminderNotificationTitle = "Habit time 🔔",
        habitReminderNotificationTextTemplate = "Time to do: %1\$s",
        habitReminderChannelName = "Habit Reminders",
        habitReminderChannelDescription = "Reminder notifications for your daily habits",
    ),
    habitSummary = HabitSummaryStrings(
        habitSummaryTitle = "Habit Summary",
        habitSummaryDateLabel = "Date",
        habitSummaryEmptyTitle = "No habits yet",
        habitSummaryEmptySubtitle = "Add a habit first in the Habit Tracker tab",
        habitSummaryDoneTemplate = "%1\$d of %2\$d done",
        habitSummaryPick = "Pick",
    ),
    pomodoro = PomodoroStrings(
        pomodoroTitle = "Pomodoro",
        pomodoroPhaseFocus = "Focus",
        pomodoroPhaseShortBreak = "Short Break",
        pomodoroPhaseLongBreak = "Long Break",
        pomodoroResetContentDesc = "Reset",
        pomodoroPauseContentDesc = "Pause",
        pomodoroStartContentDesc = "Start",
        pomodoroSkipContentDesc = "Skip",
        pomodoroSessionsTodayTemplate = "%1\$d focus sessions completed today",
        pomodoroHelpContentDesc = "What is Pomodoro?",
        pomodoroHelpTitle = "What is Pomodoro?",
        pomodoroHelpText = "A focus technique for work/study: 25 minutes of full focus, then a " +
            "5-minute break. Repeat 4 times, then you get a 15-minute long break " +
            "and the cycle starts over.\n\n" +
            "The 4 dots below the timer show your cycle progress today. " +
            "Tap the center button to start/pause, the reset icon to restart " +
            "the current phase, and the skip icon to jump to the next phase.",
        pomodoroHelpConfirm = "Got it",
        pomodoroHistoryContentDesc = "Session history",
    ),
    pomodoroSummary = PomodoroSummaryStrings(
        pomodoroSummaryTitle = "Pomodoro History",
        pomodoroSummaryDateLabel = "Date",
        pomodoroSummaryEmptyTitle = "No sessions yet",
        pomodoroSummaryEmptySubtitle = "No focus sessions completed on this date",
        pomodoroSummaryCountTemplate = "%1\$d focus sessions completed",
        pomodoroSummarySessionTimeTemplate = "Completed at %1\$s",
    ),
    drawing = DrawingStrings(
        drawingEditorTitleNew = "New Drawing",
        drawingEditorTitleEditing = "Edit Drawing",
        drawingUndoContentDesc = "Undo",
        drawingClearContentDesc = "Clear all strokes",
        drawingClearConfirmTitle = "Clear all strokes?",
        drawingClearConfirmText = "Everything on this canvas will be erased. This action cannot be undone.",
        drawingTitlePlaceholder = "Title (optional)",
    ),
    money = MoneyStrings(
        moneySummaryIncome = "Income",
        moneySummaryExpense = "Expense",
        moneySummaryBalance = "Balance",
        moneyEmptyTitle = "No transactions yet",
        moneyEmptySubtitle = "Tap + to record an income or expense",
        moneyAddContentDesc = "Add transaction",
        moneyDeleteDialogTitle = "Delete transaction?",
        moneyDeleteDialogText = "Deleted transactions cannot be recovered.",
        moneyAddTransactionTitle = "Add Transaction",
        moneyAmountLabel = "Amount",
        moneyCategoryLabel = "Category",
        moneyDateLabel = "Date",
        moneyNoteLabel = "Note",
        moneyNotePlaceholder = "Note (optional)",
        moneyCategoryFood = "Food",
        moneyCategoryTransport = "Transport",
        moneyCategoryHousing = "Housing",
        moneyCategoryEntertainment = "Entertainment",
        moneyCategoryShopping = "Shopping",
        moneyCategoryHealth = "Health",
        moneyCategoryOtherExpense = "Other",
        moneyCategoryAllowance = "Allowance",
        moneyCategorySalary = "Salary",
        moneyCategoryBonus = "Bonus",
        moneyCategoryOtherIncome = "Other",
        moneyTabTransactions = "Transactions",
        moneyTabSavings = "Savings",
        moneyTabInsights = "Insights",
        moneyStreakTemplate = "%1\$d day logging streak",
        moneyStreakEmpty = "Start logging transactions today to build a streak!",
        moneyInsightTopCategoryTemplate = "Biggest expense this month: %1\$s (%2\$s)",
        moneyInsightNoDataYet = "Log a transaction to see this month's summary",
        moneyInsightVsLastMonthUpTemplate = "Up %1\$d%% from last month",
        moneyInsightVsLastMonthDownTemplate = "Down %1\$d%% from last month",
        moneyBreakdownTitle = "Spending by Category (This Month)",
        moneyBreakdownEmpty = "No expenses yet this month",
        moneyBudgetSectionTitle = "Monthly Budgets",
        moneyBudgetPercentTemplate = "%1\$s of %2\$s (%3\$d%%)",
        moneyBudgetOverTemplate = "Over the limit by %1\$s!",
        moneyAddBudgetLabel = "Add category budget",
        moneySetBudgetTitle = "Set Budget",
        moneyBudgetLimitLabel = "Monthly limit",
        moneyDeleteBudgetContentDesc = "Delete budget",
        moneyNoBudgetsYet = "No budgets set yet",
    ),
    savings = SavingsStrings(
        savingsEmptyTitle = "No savings goals yet",
        savingsEmptySubtitle = "Tap + to create a savings or investment goal",
        savingsAddContentDesc = "Add goal",
        savingsAddGoalTitle = "New Goal",
        savingsGoalNameLabel = "Goal name",
        savingsTargetAmountLabel = "Target amount",
        savingsMonthlyContributionLabel = "Monthly contribution",
        savingsAnnualReturnLabel = "Annual return rate (%)",
        savingsAnnualReturnHint = "Optional, enter 0 for plain savings with no interest",
        savingsEstimateLabel = "Estimated time to reach",
        savingsEstimateAchieved = "Goal already reached!",
        savingsEstimateMonthsTemplate = "About %1\$d months left",
        savingsEstimateYearsMonthsTemplate = "About %1\$d years %2\$d months left",
        savingsEstimateNeverTemplate = "Won't be reached with the current contribution",
        savingsProgressTemplate = "%1\$s of %2\$s",
        savingsDeleteGoalContentDesc = "Delete goal",
        savingsDeleteGoalDialogTitle = "Delete this goal?",
        savingsDeleteGoalDialogText = "All deposit history for this goal will also be permanently deleted.",
        savingsAddDepositContentDesc = "Add deposit",
        savingsAddDepositTitle = "Add Deposit",
        savingsDepositAmountLabel = "Deposit amount",
        savingsDepositHistoryTitle = "Deposit History",
        savingsNoDepositsYet = "No deposits yet",
        savingsDeleteDepositDialogTitle = "Delete this deposit?",
        savingsDeleteDepositDialogText = "The deposit amount will be subtracted from the goal's progress.",
    ),
    jadwal = JadwalStrings(
        jadwalTitle = "Schedule",
        jadwalEmptySubtitle = "No schedule yet, tap + to add one",
        jadwalAddContentDesc = "Add schedule item",
        jadwalAddDialogTitle = "Add Schedule Item",
        jadwalTitleLabel = "Activity title",
        jadwalDateLabel = "Date",
        jadwalTimeLabel = "Time",
        jadwalTimeNoneLabel = "No specific time",
        jadwalTimeDialogTitle = "Set schedule time",
        jadwalClearTime = "Remove time",
        jadwalAdd = "Add",
        jadwalDeleteContentDesc = "Delete schedule item",
        jadwalDeleteDialogTitle = "Delete this schedule item?",
        jadwalDeleteDialogText = "Deleted schedule items cannot be recovered.",
        jadwalReminderChannelName = "Schedule Reminders",
        jadwalReminderChannelDescription = "Notifications when your scheduled item is due",
        jadwalReminderNotificationTitle = "Schedule time! ⏰",
        jadwalReminderNotificationTextTemplate = "Time for: %1\$s",
    ),
    targetHidup = TargetHidupStrings(
        targetHidupTitle = "Life Goals",
        targetHidupEmptySubtitle = "No goals yet, tap + to add one",
        targetHidupAddContentDesc = "Add goal",
        targetHidupAddDialogTitle = "Add Life Goal",
        targetHidupTitleLabel = "Goal name",
        targetHidupTargetDateLabel = "Target date",
        targetHidupTargetDateNoneLabel = "No deadline",
        targetHidupProgressLabel = "Progress",
        targetHidupProgressTemplate = "%1\$d%% complete",
        targetHidupAdd = "Add",
        targetHidupEditDialogTitle = "Update Progress",
        targetHidupDeleteContentDesc = "Delete goal",
        targetHidupDeleteDialogTitle = "Delete this goal?",
        targetHidupDeleteDialogText = "Deleted goals cannot be recovered.",
        targetHidupCompletedLabel = "Achieved! 🎉",
        targetHidupDaysLeftTemplate = "%1\$d days left",
        targetHidupOverdueLabel = "Past deadline",
    ),
    statistik = StatistikStrings(
        statistikTitle = "Stats Dashboard",
        statistikTotalNotes = "Total Notes",
        statistikTotalPomodoro = "Total Pomodoro Sessions",
        statistikActiveHabits = "Active Habits",
        statistikLongestStreak = "Longest Streak",
        statistikStreakTemplate = "%1\$d days",
        statistikGoalsAchieved = "Goals Achieved",
        statistikPomodoroChartTitle = "Pomodoro Sessions (Last 7 Days)",
        statistikHabitChartTitle = "Today's Habit Completion",
        statistikTodayLabel = "Today",
        statistikDonutCompletedLabel = "Done",
        statistikDonutRemainingLabel = "Not yet",
        statistikDonutTodayTemplate = "%1\$d of %2\$d habits done today",
        statistikDonutAvgTemplate = "7-day average: %1\$d%%",
    ),
    aiAssistant = AiAssistantStrings(
        aiAssistantTitle = "AI Assistant",
        aiAssistantEmptySubtitle = "Ask anything — this AI assistant can help with notes, your schedule, or just chat.",
        aiAssistantInputPlaceholder = "Type a message...",
        aiAssistantSendContentDesc = "Send",
        aiAssistantClearContentDesc = "Clear chat",
        aiAssistantClearDialogTitle = "Clear the whole chat?",
        aiAssistantClearDialogText = "Your chat history with the AI Assistant will be permanently deleted.",
        aiAssistantRateLimitMessage = "Daily message limit reached. Try again tomorrow.",
        aiAssistantErrorPrefixTemplate = "Something went wrong: %1\$s",
        aiAssistantThinkingLabel = "Typing...",
    ),
    belajar = BelajarStrings(
        belajarTitle = "Study",
        belajarSubjectMatematika = "Mathematics",
        belajarSubjectBahasaInggris = "English",
        belajarSubjectFisika = "Physics",
        belajarSubjectKimia = "Chemistry",
        belajarSubjectMusik = "Music",
        belajarSubjectSeni = "Art",
    ),
    bahasaInggrisGame = BahasaInggrisGameStrings(
        bahasaInggrisGameKosakata = "Vocabulary",
        bahasaInggrisGameTataBahasa = "Grammar",
        bahasaInggrisGameSusunKalimat = "Sentence Builder",
        bahasaInggrisGameListening = "Listening & Pronunciation",
    ),
    kosakata = KosakataStrings(
        kosakataDescription = "Test your English vocabulary with multiple choice questions.",
        kosakataScoreTemplate = "Score: %1\$d of %2\$d correct",
        kosakataQuestionTitleTemplate = "Question %1\$d",
        kosakataCorrectFeedback = "Correct! 🎉",
        kosakataIncorrectFeedback = "Not quite. The correct answer is marked in green.",
        kosakataNextQuestion = "Next Question",
        kosakataBackToList = "Back to Question List",
        kosakataAllDoneMessage = "You've correctly answered every question! 🎉",
    ),
    tataBahasa = TataBahasaStrings(
        tataBahasaDescription = "Practice your English grammar by completing sentences.",
        tataBahasaScoreTemplate = "Score: %1\$d of %2\$d correct",
        tataBahasaQuestionTitleTemplate = "Question %1\$d",
        tataBahasaCorrectFeedback = "Correct! 🎉",
        tataBahasaIncorrectFeedback = "Not quite. The correct answer is marked in green.",
        tataBahasaNextQuestion = "Next Question",
        tataBahasaBackToList = "Back to Question List",
        tataBahasaAllDoneMessage = "You've correctly answered every question! 🎉",
    ),
    susunKalimat = SusunKalimatStrings(
        susunKalimatDescription = "Arrange the scrambled words into a correct English sentence.",
        susunKalimatScoreTemplate = "Score: %1\$d of %2\$d correct",
        susunKalimatQuestionTitleTemplate = "Sentence %1\$d",
        susunKalimatCorrectFeedback = "Correct! 🎉",
        susunKalimatIncorrectFeedback = "Not quite. The correct order:",
        susunKalimatNextQuestion = "Next Sentence",
        susunKalimatBackToList = "Back to Sentence List",
        susunKalimatAllDoneMessage = "You've correctly built every sentence! 🎉",
        susunKalimatCheckButton = "Check Answer",
        susunKalimatResetButton = "Reset",
        susunKalimatHintLabel = "Hint (Indonesian):",
    ),
    listening = ListeningStrings(
        listeningDescription = "Listen to an English word or phrase, then pick the correct spelling.",
        listeningScoreTemplate = "Score: %1\$d of %2\$d correct",
        listeningQuestionTitleTemplate = "Question %1\$d",
        listeningCorrectFeedback = "Correct! 🎉",
        listeningIncorrectFeedback = "Not quite. The correct answer is marked in green.",
        listeningNextQuestion = "Next Question",
        listeningBackToList = "Back to Question List",
        listeningAllDoneMessage = "You've correctly answered every question! 🎉",
        listeningPlayButton = "Play Sound",
        listeningPrompt = "Listen, then pick the correct spelling:",
    ),
    fisikaGame = FisikaGameStrings(
        fisikaGameBesaran = "Quantities & Units",
        fisikaGameGerak = "Motion & Forces",
        fisikaGameEnergi = "Energy & Work",
        fisikaGameListrik = "Electricity & Magnetism",
    ),
    fisikaBesaran = FisikaBesaranStrings(
        fisikaBesaranDescription = "Test your grasp of physical quantities, units, and measuring tools.",
        fisikaBesaranScoreTemplate = "Score: %1\$d of %2\$d correct",
        fisikaBesaranQuestionTitleTemplate = "Question %1\$d",
        fisikaBesaranCorrectFeedback = "Correct! 🎉",
        fisikaBesaranIncorrectFeedback = "Not quite. The correct answer is marked in green.",
        fisikaBesaranNextQuestion = "Next Question",
        fisikaBesaranBackToList = "Back to Question List",
        fisikaBesaranAllDoneMessage = "You've correctly answered every question! 🎉",
    ),
    fisikaGerak = FisikaGerakStrings(
        fisikaGerakDescription = "Practice motion, velocity, forces, and Newton's laws.",
        fisikaGerakScoreTemplate = "Score: %1\$d of %2\$d correct",
        fisikaGerakQuestionTitleTemplate = "Question %1\$d",
        fisikaGerakCorrectFeedback = "Correct! 🎉",
        fisikaGerakIncorrectFeedback = "Not quite. The correct answer is marked in green.",
        fisikaGerakNextQuestion = "Next Question",
        fisikaGerakBackToList = "Back to Question List",
        fisikaGerakAllDoneMessage = "You've correctly answered every question! 🎉",
    ),
    fisikaEnergi = FisikaEnergiStrings(
        fisikaEnergiDescription = "Understand work, energy, and power through multiple choice questions.",
        fisikaEnergiScoreTemplate = "Score: %1\$d of %2\$d correct",
        fisikaEnergiQuestionTitleTemplate = "Question %1\$d",
        fisikaEnergiCorrectFeedback = "Correct! 🎉",
        fisikaEnergiIncorrectFeedback = "Not quite. The correct answer is marked in green.",
        fisikaEnergiNextQuestion = "Next Question",
        fisikaEnergiBackToList = "Back to Question List",
        fisikaEnergiAllDoneMessage = "You've correctly answered every question! 🎉",
    ),
    fisikaListrik = FisikaListrikStrings(
        fisikaListrikDescription = "Test your knowledge of electricity, current, voltage, resistance, and magnets.",
        fisikaListrikScoreTemplate = "Score: %1\$d of %2\$d correct",
        fisikaListrikQuestionTitleTemplate = "Question %1\$d",
        fisikaListrikCorrectFeedback = "Correct! 🎉",
        fisikaListrikIncorrectFeedback = "Not quite. The correct answer is marked in green.",
        fisikaListrikNextQuestion = "Next Question",
        fisikaListrikBackToList = "Back to Question List",
        fisikaListrikAllDoneMessage = "You've correctly answered every question! 🎉",
    ),
    kimiaGame = KimiaGameStrings(
        kimiaGameAtom = "Atoms & Elements",
        kimiaGameIkatan = "Bonds & Reactions",
        kimiaGameAsamBasa = "Acids & Bases",
        kimiaGameWujud = "States & Mixtures",
    ),
    kimiaAtom = KimiaAtomStrings(
        kimiaAtomDescription = "Learn atomic structure, subatomic particles, element symbols, and the periodic table.",
        kimiaAtomScoreTemplate = "Score: %1\$d of %2\$d correct",
        kimiaAtomQuestionTitleTemplate = "Question %1\$d",
        kimiaAtomCorrectFeedback = "Correct! 🎉",
        kimiaAtomIncorrectFeedback = "Not quite. The correct answer is marked in green.",
        kimiaAtomNextQuestion = "Next Question",
        kimiaAtomBackToList = "Back to Question List",
        kimiaAtomAllDoneMessage = "You've correctly answered every question! 🎉",
    ),
    kimiaIkatan = KimiaIkatanStrings(
        kimiaIkatanDescription = "Test your grasp of chemical bonds, compound formulas, and reactions.",
        kimiaIkatanScoreTemplate = "Score: %1\$d of %2\$d correct",
        kimiaIkatanQuestionTitleTemplate = "Question %1\$d",
        kimiaIkatanCorrectFeedback = "Correct! 🎉",
        kimiaIkatanIncorrectFeedback = "Not quite. The correct answer is marked in green.",
        kimiaIkatanNextQuestion = "Next Question",
        kimiaIkatanBackToList = "Back to Question List",
        kimiaIkatanAllDoneMessage = "You've correctly answered every question! 🎉",
    ),
    kimiaAsamBasa = KimiaAsamBasaStrings(
        kimiaAsamBasaDescription = "Recognize acids, bases, neutral solutions, pH, and indicators.",
        kimiaAsamBasaScoreTemplate = "Score: %1\$d of %2\$d correct",
        kimiaAsamBasaQuestionTitleTemplate = "Question %1\$d",
        kimiaAsamBasaCorrectFeedback = "Correct! 🎉",
        kimiaAsamBasaIncorrectFeedback = "Not quite. The correct answer is marked in green.",
        kimiaAsamBasaNextQuestion = "Next Question",
        kimiaAsamBasaBackToList = "Back to Question List",
        kimiaAsamBasaAllDoneMessage = "You've correctly answered every question! 🎉",
    ),
    kimiaWujud = KimiaWujudStrings(
        kimiaWujudDescription = "Understand changes of state and homogeneous vs heterogeneous mixtures.",
        kimiaWujudScoreTemplate = "Score: %1\$d of %2\$d correct",
        kimiaWujudQuestionTitleTemplate = "Question %1\$d",
        kimiaWujudCorrectFeedback = "Correct! 🎉",
        kimiaWujudIncorrectFeedback = "Not quite. The correct answer is marked in green.",
        kimiaWujudNextQuestion = "Next Question",
        kimiaWujudBackToList = "Back to Question List",
        kimiaWujudAllDoneMessage = "You've correctly answered every question! 🎉",
    ),
    musikGame = MusikGameStrings(
        musikGameNotNada = "Notes & Pitch",
        musikGameRitme = "Rhythm & Tempo",
        musikGameAlat = "Instruments",
        musikGameTeori = "Music Theory",
    ),
    musikNotNada = MusikNotNadaStrings(
        musikNotNadaDescription = "Get to know scales, notation, pitches, and musical symbols.",
        musikNotNadaScoreTemplate = "Score: %1\$d of %2\$d correct",
        musikNotNadaQuestionTitleTemplate = "Question %1\$d",
        musikNotNadaCorrectFeedback = "Correct! 🎉",
        musikNotNadaIncorrectFeedback = "Not quite. The correct answer is marked in green.",
        musikNotNadaNextQuestion = "Next Question",
        musikNotNadaBackToList = "Back to Question List",
        musikNotNadaAllDoneMessage = "You've correctly answered every question! 🎉",
    ),
    musikRitme = MusikRitmeStrings(
        musikRitmeDescription = "Learn tempo, time signature, beat, and rhythm terms in music.",
        musikRitmeScoreTemplate = "Score: %1\$d of %2\$d correct",
        musikRitmeQuestionTitleTemplate = "Question %1\$d",
        musikRitmeCorrectFeedback = "Correct! 🎉",
        musikRitmeIncorrectFeedback = "Not quite. The correct answer is marked in green.",
        musikRitmeNextQuestion = "Next Question",
        musikRitmeBackToList = "Back to Question List",
        musikRitmeAllDoneMessage = "You've correctly answered every question! 🎉",
    ),
    musikAlat = MusikAlatStrings(
        musikAlatDescription = "Test your knowledge of musical instruments and how they are played.",
        musikAlatScoreTemplate = "Score: %1\$d of %2\$d correct",
        musikAlatQuestionTitleTemplate = "Question %1\$d",
        musikAlatCorrectFeedback = "Correct! 🎉",
        musikAlatIncorrectFeedback = "Not quite. The correct answer is marked in green.",
        musikAlatNextQuestion = "Next Question",
        musikAlatBackToList = "Back to Question List",
        musikAlatAllDoneMessage = "You've correctly answered every question! 🎉",
    ),
    musikTeori = MusikTeoriStrings(
        musikTeoriDescription = "Understand melody, harmony, chords, dynamics, and timbre.",
        musikTeoriScoreTemplate = "Score: %1\$d of %2\$d correct",
        musikTeoriQuestionTitleTemplate = "Question %1\$d",
        musikTeoriCorrectFeedback = "Correct! 🎉",
        musikTeoriIncorrectFeedback = "Not quite. The correct answer is marked in green.",
        musikTeoriNextQuestion = "Next Question",
        musikTeoriBackToList = "Back to Question List",
        musikTeoriAllDoneMessage = "You've correctly answered every question! 🎉",
    ),
    seniGame = SeniGameStrings(
        seniGameWarna = "Color",
        seniGameUnsur = "Elements of Art",
        seniGameTeknik = "Techniques & Media",
        seniGameAliran = "Movements & Figures",
    ),
    seniWarna = SeniWarnaStrings(
        seniWarnaDescription = "Learn primary and secondary colors, warm/cool colors, and the color wheel.",
        seniWarnaScoreTemplate = "Score: %1\$d of %2\$d correct",
        seniWarnaQuestionTitleTemplate = "Question %1\$d",
        seniWarnaCorrectFeedback = "Correct! 🎉",
        seniWarnaIncorrectFeedback = "Not quite. The correct answer is marked in green.",
        seniWarnaNextQuestion = "Next Question",
        seniWarnaBackToList = "Back to Question List",
        seniWarnaAllDoneMessage = "You've correctly answered every question! 🎉",
    ),
    seniUnsur = SeniUnsurStrings(
        seniUnsurDescription = "Get to know the elements of art: point, line, shape, texture, and space.",
        seniUnsurScoreTemplate = "Score: %1\$d of %2\$d correct",
        seniUnsurQuestionTitleTemplate = "Question %1\$d",
        seniUnsurCorrectFeedback = "Correct! 🎉",
        seniUnsurIncorrectFeedback = "Not quite. The correct answer is marked in green.",
        seniUnsurNextQuestion = "Next Question",
        seniUnsurBackToList = "Back to Question List",
        seniUnsurAllDoneMessage = "You've correctly answered every question! 🎉",
    ),
    seniTeknik = SeniTeknikStrings(
        seniTeknikDescription = "Test your knowledge of art-making techniques and media.",
        seniTeknikScoreTemplate = "Score: %1\$d of %2\$d correct",
        seniTeknikQuestionTitleTemplate = "Question %1\$d",
        seniTeknikCorrectFeedback = "Correct! 🎉",
        seniTeknikIncorrectFeedback = "Not quite. The correct answer is marked in green.",
        seniTeknikNextQuestion = "Next Question",
        seniTeknikBackToList = "Back to Question List",
        seniTeknikAllDoneMessage = "You've correctly answered every question! 🎉",
    ),
    seniAliran = SeniAliranStrings(
        seniAliranDescription = "Get to know painting movements and famous artists.",
        seniAliranScoreTemplate = "Score: %1\$d of %2\$d correct",
        seniAliranQuestionTitleTemplate = "Question %1\$d",
        seniAliranCorrectFeedback = "Correct! 🎉",
        seniAliranIncorrectFeedback = "Not quite. The correct answer is marked in green.",
        seniAliranNextQuestion = "Next Question",
        seniAliranBackToList = "Back to Question List",
        seniAliranAllDoneMessage = "You've correctly answered every question! 🎉",
    ),
    mathGame = MathGameStrings(
        mathGameHitungCepat = "Speed Math",
        mathGameHots = "HOTS Questions",
        mathGameLogika = "Logic Puzzles",
        mathGameTekaTeki = "Riddles",
        mathGamePuzzle = "Puzzle Game",
    ),
    speedMath = SpeedMathStrings(
        speedMathDescription = "Answer as fast as you can before time runs out. Each question gives you less time!",
        speedMathStartButton = "Start",
        speedMathBestScoreTemplate = "High score: %1\$d",
        speedMathScoreTemplate = "Score: %1\$d",
        speedMathGameOverTitle = "Game Over",
        speedMathNewHighScore = "New high score!",
        speedMathFinalScoreTemplate = "Final score: %1\$d",
        speedMathAverageTimeTemplate = "Average %1\$s sec per question",
        speedMathPlayAgain = "Play Again",
    ),
    hots = HotsStrings(
        hotsDescription = "Work it out on paper, then enter your answer here.",
        hotsScoreTemplate = "Score: %1\$d of %2\$d correct",
        hotsQuestionTitleTemplate = "Question %1\$d",
        hotsAnswerLabel = "Your answer",
        hotsCheckAnswerButton = "Check Answer",
        hotsCorrectFeedback = "Correct! 🎉",
        hotsIncorrectFeedbackTemplate = "Not quite. The correct answer: %1\$s",
        hotsNextQuestion = "Next Question",
        hotsBackToList = "Back to Question List",
        hotsAllDoneMessage = "You've correctly solved every question! 🎉",
    ),
    logika = LogikaStrings(
        logikaDescription = "Sharpen your logical thinking with shape patterns, puzzles, and deduction questions.",
        logikaScoreTemplate = "Score: %1\$d of %2\$d correct",
        logikaPuzzleTitleTemplate = "Question %1\$d",
        logikaCorrectFeedback = "Correct! 🎉",
        logikaIncorrectFeedback = "Not quite. The correct answer is marked in green.",
        logikaNextPuzzle = "Next Question",
        logikaBackToList = "Back to Question List",
        logikaAllDoneMessage = "You've correctly solved every question! 🎉",
        logikaChooseNextLabel = "Pick the correct continuation:",
        logikaChooseOddLabel = "Pick the one that's different:",
    ),
    tekaTeki = TekaTekiStrings(
        tekaTekiDescription = "Solve these classic riddles with creative thinking. Stuck? Try the hint!",
        tekaTekiScoreTemplate = "Score: %1\$d of %2\$d correct",
        tekaTekiQuestionTitleTemplate = "Riddle %1\$d",
        tekaTekiAnswerLabel = "Your answer",
        tekaTekiCheckAnswerButton = "Check Answer",
        tekaTekiCorrectFeedback = "Correct! 🎉",
        tekaTekiIncorrectFeedbackTemplate = "Not quite. The answer: %1\$s",
        tekaTekiNextQuestion = "Next Riddle",
        tekaTekiBackToList = "Back to Riddle List",
        tekaTekiAllDoneMessage = "You've solved every riddle! 🎉",
        tekaTekiShowHintButton = "Show Hint",
    ),
    puzzle = PuzzleStrings(
        puzzleDescription = "Rearrange numbers 1 to 15 by sliding tiles into the empty space.",
        puzzleMovesTemplate = "Moves: %1\$d",
        puzzleTimeTemplate = "Time: %1\$s",
        puzzleBestMovesTemplate = "Best: %1\$d moves",
        puzzleNoBestYet = "No record yet",
        puzzleSolvedTitle = "Solved! 🎉",
        puzzleNewBestMessage = "New record!",
        puzzleResultTemplate = "%1\$d moves in %2\$s",
        puzzlePlayAgain = "Shuffle Again",
        puzzleShuffleContentDesc = "Reshuffle",
    ),
)

val LocalStrings = compositionLocalOf { IndonesianStrings }
